<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SunderSdkReference>true</SunderSdkReference>
    <SunderPackageProject Condition="'$(BuildAuthorSamplePackage)' == 'true'">true</SunderPackageProject>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sunder.Package.Agent.Contracts\Sunder.Package.Agent.Contracts.csproj" />
  </ItemGroup>
</Project>
