// <auto-generated />
using Sunder.Package.Agent.Contracts.Contracts;
using Sunder.Package.Agent.Contracts.Models;
using Sunder.Sdk.Rpc;

namespace Sunder.Package.Agent.Protocol;

public static class AgentExecutionFacetIds
{
    public const string ProcessExecution = "process-execution";
    public const string ResourceResolution = "resource-resolution";
    public const string ResourceAuthority = "resource-authority";
    public const string ExecutionScope = "execution-scope";
    public const string PathMapping = "path-mapping";
    public const string PathEnvironment = "path-environment";
    public const string RangedFileRead = "ranged-file-read";
    public const string LegacyFileSearch = "legacy-file-search";
    public const string StructuredFileSearch = "structured-file-search";
    public const string ScopedInstructionDiscovery = "scoped-instruction-discovery";
}

public static class AgentExecutionTargetRpc
{
    public const string ServiceId = "execution-target";

    public static ISunderRpcServiceHandler CreateHandler(IAgentExecutionTarget target)
    {
        var descriptor = WithFacets(target);
        return AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentExecutionTargetDescriptor>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(descriptor))
            .AddUnary<AgentExecutionTargetContextWire, AgentRpcOptional<string>>(ServiceId, "configuration-generation", async (_, request, token) => new(true, await target.GetConfigurationGenerationAsync(request.ToContext(), token).ConfigureAwait(false)))
            .AddUnary<AgentExecutionTargetContextWire, AgentExecutionTargetReadiness>(ServiceId, "readiness", (_, request, token) => target.GetReadinessAsync(request.ToContext(), token))
            .AddUnary<AgentExecutionTargetContextWire, AgentExecutionShellDescriptor>(ServiceId, "shell", (_, request, token) => target.GetShellAsync(request.ToContext(), token))
            .AddUnary<ExecutionPathRequest, AgentResolvedResourceWire>(ServiceId, "resolve-file", async (_, request, token) => AgentResolvedResourceWire.FromResource(
                await target.ResolveFileResourceAsync(request.Context.ToContext(), request.Path, token).ConfigureAwait(false)))
            .AddUnary<ExecutionShellRequest, AgentShellCommandResult>(ServiceId, "execute-shell", (_, request, token) => target.ExecuteShellAsync(request.Context.ToContext(), request.Request, token))
            .AddUnary<ExecutionFileReadRequest, AgentFileReadResult>(ServiceId, "read-file", (_, request, token) => target.ReadFileAsync(request.Context.ToContext(), request.Request, token))
            .AddUnary<ExecutionFileWriteRequest, AgentFileMutationResultWire>(ServiceId, "write-file", async (_, request, token) => AgentFileMutationResultWire.FromResult(
                await target.WriteFileAsync(request.Context.ToContext(), request.Request, token).ConfigureAwait(false)))
            .AddUnary<ExecutionFileDeleteRequest, AgentFileMutationResultWire>(ServiceId, "delete-file", async (_, request, token) => AgentFileMutationResultWire.FromResult(
                await target.DeleteFileAsync(request.Context.ToContext(), request.Request, token).ConfigureAwait(false)))
            .AddUnary<ExecutionProcessRequest, AgentShellCommandResult>(ServiceId, "execute-process", (_, request, token) => Require<IAgentProcessExecutionTarget>(target, descriptor, AgentExecutionFacetIds.ProcessExecution).ExecuteProcessAsync(request.Context.ToContext(), request.Request, token))
            .AddUnary<ExecutionResourcesRequest, IReadOnlyList<AgentResolvedExecutionResource>>(ServiceId, "resolve-resources", (_, request, token) => Require<IAgentExecutionResourceResolver>(target, descriptor, AgentExecutionFacetIds.ResourceResolution).ResolveResourcesAsync(request.Context.ToContext(), request.Resources, token))
            .AddUnary<AgentExecutionTargetContextWire, AgentResourceAuthorityValidation>(ServiceId, "validate-resource-authority", (_, request, token) => Require<IAgentResourceAuthorityExecutionTarget>(target, descriptor, AgentExecutionFacetIds.ResourceAuthority).ValidateResourceAuthorityAsync(request.ToContext(), token))
            .AddUnary<ResourceCapabilitiesRequest, AgentRpcEmpty>(ServiceId, "release-resource-authority", (_, request, _) =>
            {
                Require<IAgentResourceAuthorityExecutionTarget>(target, descriptor, AgentExecutionFacetIds.ResourceAuthority).ReleaseResourceAuthority(request.Capabilities);
                return ValueTask.FromResult(new AgentRpcEmpty());
            })
            .AddUnary<AgentExecutionTargetContextWire, AgentExecutionScopeDescriptor>(ServiceId, "execution-scope", (_, request, token) => Require<IAgentExecutionScopeProvider>(target, descriptor, AgentExecutionFacetIds.ExecutionScope).GetExecutionScopeAsync(request.ToContext(), token))
            .AddUnary<ExecutionPathRequest, AgentExecutionPathMapping>(ServiceId, "map-path", (_, request, token) => Require<IAgentExecutionPathMapper>(target, descriptor, AgentExecutionFacetIds.PathMapping).MapToHostPathAsync(request.Context.ToContext(), request.Path, token))
            .AddUnary<AgentExecutionTargetContextWire, IReadOnlyList<string>>(ServiceId, "list-path", (_, request, token) => Require<IAgentExecutionPathEnvironment>(target, descriptor, AgentExecutionFacetIds.PathEnvironment).ListPathEntriesAsync(request.ToContext(), token))
            .AddUnary<ExecutionPathRequest, AgentRpcEmpty>(ServiceId, "add-path", async (_, request, token) =>
            {
                await Require<IAgentExecutionPathEnvironment>(target, descriptor, AgentExecutionFacetIds.PathEnvironment).AddPathEntryAsync(request.Context.ToContext(), request.Path, token).ConfigureAwait(false);
                return new AgentRpcEmpty();
            })
            .AddUnary<ExecutionFileSearchProcessRequest, AgentFileSearchProcessResult>(ServiceId, "legacy-file-search", (_, request, token) => Require<IAgentFileSearchExecutionTarget>(target, descriptor, AgentExecutionFacetIds.LegacyFileSearch).ExecuteFileSearchProcessAsync(request.Context.ToContext(), request.Request, token))
            .AddUnary<ExecutionFileSearchRequest, AgentFileSearchResult>(ServiceId, "structured-file-search", (_, request, token) => Require<IAgentStructuredFileSearchExecutionTarget>(target, descriptor, AgentExecutionFacetIds.StructuredFileSearch).ExecuteFileSearchAsync(request.Context.ToContext(), request.Request, token))
            .AddUnary<ExecutionInstructionDiscoveryRequest, AgentScopedInstructionDiscoveryResult>(ServiceId, "discover-instructions", (_, request, token) => Require<IAgentScopedInstructionDiscoveryTarget>(target, descriptor, AgentExecutionFacetIds.ScopedInstructionDiscovery).DiscoverScopedInstructionsAsync(request.Context.ToContext(), request.Request, token))
            .Build();
    }

    public static bool SupportsFacet(IAgentExecutionTarget target, string facetId)
    {
        ArgumentNullException.ThrowIfNull(target);
        ArgumentException.ThrowIfNullOrWhiteSpace(facetId);
        if (target is AgentExecutionTargetRpcClient || target.Descriptor.Facets.Count > 0)
        {
            return target.Descriptor.SupportsFacet(facetId);
        }

        return facetId switch
        {
            AgentExecutionFacetIds.ProcessExecution => target is IAgentProcessExecutionTarget,
            AgentExecutionFacetIds.ResourceResolution => target is IAgentExecutionResourceResolver,
            AgentExecutionFacetIds.ResourceAuthority => target is IAgentResourceAuthorityExecutionTarget,
            AgentExecutionFacetIds.ExecutionScope => target is IAgentExecutionScopeProvider,
            AgentExecutionFacetIds.PathMapping => target is IAgentExecutionPathMapper,
            AgentExecutionFacetIds.PathEnvironment => target is IAgentExecutionPathEnvironment,
            AgentExecutionFacetIds.RangedFileRead => target is IAgentRangedFileExecutionTarget,
            AgentExecutionFacetIds.LegacyFileSearch => target is IAgentFileSearchExecutionTarget,
            AgentExecutionFacetIds.StructuredFileSearch => target is IAgentStructuredFileSearchExecutionTarget,
            AgentExecutionFacetIds.ScopedInstructionDiscovery => target is IAgentScopedInstructionDiscoveryTarget,
            _ => false,
        };
    }

    private static AgentExecutionTargetDescriptor WithFacets(IAgentExecutionTarget target)
    {
        var facets = target.Descriptor.Facets.Count > 0
            ? target.Descriptor.Facets
            : new[]
            {
                SupportsFacet(target, AgentExecutionFacetIds.ProcessExecution) ? AgentExecutionFacetIds.ProcessExecution : null,
                SupportsFacet(target, AgentExecutionFacetIds.ResourceResolution) ? AgentExecutionFacetIds.ResourceResolution : null,
                SupportsFacet(target, AgentExecutionFacetIds.ResourceAuthority) ? AgentExecutionFacetIds.ResourceAuthority : null,
                SupportsFacet(target, AgentExecutionFacetIds.ExecutionScope) ? AgentExecutionFacetIds.ExecutionScope : null,
                SupportsFacet(target, AgentExecutionFacetIds.PathMapping) ? AgentExecutionFacetIds.PathMapping : null,
                SupportsFacet(target, AgentExecutionFacetIds.PathEnvironment) ? AgentExecutionFacetIds.PathEnvironment : null,
                SupportsFacet(target, AgentExecutionFacetIds.RangedFileRead) ? AgentExecutionFacetIds.RangedFileRead : null,
                SupportsFacet(target, AgentExecutionFacetIds.LegacyFileSearch) ? AgentExecutionFacetIds.LegacyFileSearch : null,
                SupportsFacet(target, AgentExecutionFacetIds.StructuredFileSearch) ? AgentExecutionFacetIds.StructuredFileSearch : null,
                SupportsFacet(target, AgentExecutionFacetIds.ScopedInstructionDiscovery) ? AgentExecutionFacetIds.ScopedInstructionDiscovery : null,
            }.Where(static facet => facet is not null).Select(static facet => facet!).ToArray();
        return target.Descriptor with { Facets = facets };
    }

    private static TFacet Require<TFacet>(IAgentExecutionTarget target, AgentExecutionTargetDescriptor descriptor, string facetId)
        where TFacet : class
        => descriptor.SupportsFacet(facetId) && target is TFacet facet
            ? facet
            : throw new SunderRpcException(new SunderRpcError(
                SunderRpcErrorKind.Domain,
                "agent.execution.facet-unavailable",
                $"Execution target facet '{facetId}' is unavailable."));
}

public sealed class AgentExecutionTargetRpcClient :
    IAgentProcessExecutionTarget,
    IAgentExecutionResourceResolver,
    IAgentResourceAuthorityExecutionTarget,
    IAgentExecutionScopeProvider,
    IAgentExecutionPathMapper,
    IAgentExecutionPathEnvironment,
    IAgentRangedFileExecutionTarget,
    IAgentFileSearchExecutionTarget,
    IAgentStructuredFileSearchExecutionTarget,
    IAgentScopedInstructionDiscoveryTarget
{
    private readonly ISunderRpcClient _client;
    private readonly SunderRpcEndpointReference _endpoint;
    private AgentExecutionTargetDescriptor? _descriptor;

    public AgentExecutionTargetRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint)
    {
        _client = client;
        _endpoint = endpoint;
    }

    public AgentExecutionTargetDescriptor Descriptor => _descriptor ??= Invoke<AgentRpcEmpty, AgentExecutionTargetDescriptor>("describe", new AgentRpcEmpty());
    public async ValueTask<string?> GetConfigurationGenerationAsync(AgentExecutionTargetContext context, CancellationToken cancellationToken = default)
        => (await InvokeAsync<AgentExecutionTargetContextWire, AgentRpcOptional<string>>("configuration-generation", AgentExecutionTargetContextWire.FromContext(context), cancellationToken).ConfigureAwait(false)).Value;
    public ValueTask<AgentExecutionTargetReadiness> GetReadinessAsync(AgentExecutionTargetContext context, CancellationToken cancellationToken = default) => InvokeAsync<AgentExecutionTargetContextWire, AgentExecutionTargetReadiness>("readiness", AgentExecutionTargetContextWire.FromContext(context), cancellationToken);
    public ValueTask<AgentExecutionShellDescriptor> GetShellAsync(AgentExecutionTargetContext context, CancellationToken cancellationToken = default) => InvokeAsync<AgentExecutionTargetContextWire, AgentExecutionShellDescriptor>("shell", AgentExecutionTargetContextWire.FromContext(context), cancellationToken);
    public async ValueTask<AgentResolvedResource> ResolveFileResourceAsync(AgentExecutionTargetContext context, string path, CancellationToken cancellationToken = default)
        => (await InvokeAsync<ExecutionPathRequest, AgentResolvedResourceWire>("resolve-file", new(AgentExecutionTargetContextWire.FromContext(context), path), cancellationToken).ConfigureAwait(false)).ToResource();
    public ValueTask<AgentShellCommandResult> ExecuteShellAsync(AgentExecutionTargetContext context, AgentShellCommandRequest request, CancellationToken cancellationToken = default) => InvokeAsync<ExecutionShellRequest, AgentShellCommandResult>("execute-shell", new(AgentExecutionTargetContextWire.FromContext(context), request), cancellationToken);
    public ValueTask<AgentFileReadResult> ReadFileAsync(AgentExecutionTargetContext context, AgentFileReadRequest request, CancellationToken cancellationToken = default) => InvokeAsync<ExecutionFileReadRequest, AgentFileReadResult>("read-file", new(AgentExecutionTargetContextWire.FromContext(context), request), cancellationToken);
    public async ValueTask<AgentFileMutationResult> WriteFileAsync(AgentExecutionTargetContext context, AgentFileWriteRequest request, CancellationToken cancellationToken = default)
        => (await InvokeAsync<ExecutionFileWriteRequest, AgentFileMutationResultWire>("write-file", new(AgentExecutionTargetContextWire.FromContext(context), request), cancellationToken).ConfigureAwait(false)).ToResult();
    public async ValueTask<AgentFileMutationResult> DeleteFileAsync(AgentExecutionTargetContext context, AgentFileDeleteRequest request, CancellationToken cancellationToken = default)
        => (await InvokeAsync<ExecutionFileDeleteRequest, AgentFileMutationResultWire>("delete-file", new(AgentExecutionTargetContextWire.FromContext(context), request), cancellationToken).ConfigureAwait(false)).ToResult();
    public ValueTask<AgentShellCommandResult> ExecuteProcessAsync(AgentExecutionTargetContext context, AgentProcessCommandRequest request, CancellationToken cancellationToken = default) => InvokeFacetAsync<ExecutionProcessRequest, AgentShellCommandResult>(AgentExecutionFacetIds.ProcessExecution, "execute-process", new(AgentExecutionTargetContextWire.FromContext(context), request), cancellationToken);
    public ValueTask<IReadOnlyList<AgentResolvedExecutionResource>> ResolveResourcesAsync(AgentExecutionTargetContext context, IReadOnlyList<AgentExecutionResourceDescriptor> resources, CancellationToken cancellationToken = default) => InvokeFacetAsync<ExecutionResourcesRequest, IReadOnlyList<AgentResolvedExecutionResource>>(AgentExecutionFacetIds.ResourceResolution, "resolve-resources", new(AgentExecutionTargetContextWire.FromContext(context), resources), cancellationToken);
    public ValueTask<AgentResourceAuthorityValidation> ValidateResourceAuthorityAsync(AgentExecutionTargetContext context, CancellationToken cancellationToken = default) => InvokeFacetAsync<AgentExecutionTargetContextWire, AgentResourceAuthorityValidation>(AgentExecutionFacetIds.ResourceAuthority, "validate-resource-authority", AgentExecutionTargetContextWire.FromContext(context), cancellationToken);
    public void ReleaseResourceAuthority(IReadOnlyList<string> resourceCapabilities) => _ = InvokeFacet<ResourceCapabilitiesRequest, AgentRpcEmpty>(AgentExecutionFacetIds.ResourceAuthority, "release-resource-authority", new(resourceCapabilities));
    public ValueTask<AgentExecutionScopeDescriptor> GetExecutionScopeAsync(AgentExecutionTargetContext context, CancellationToken cancellationToken = default) => InvokeFacetAsync<AgentExecutionTargetContextWire, AgentExecutionScopeDescriptor>(AgentExecutionFacetIds.ExecutionScope, "execution-scope", AgentExecutionTargetContextWire.FromContext(context), cancellationToken);
    public ValueTask<AgentExecutionPathMapping> MapToHostPathAsync(AgentExecutionTargetContext context, string executionPath, CancellationToken cancellationToken = default) => InvokeFacetAsync<ExecutionPathRequest, AgentExecutionPathMapping>(AgentExecutionFacetIds.PathMapping, "map-path", new(AgentExecutionTargetContextWire.FromContext(context), executionPath), cancellationToken);
    public ValueTask<IReadOnlyList<string>> ListPathEntriesAsync(AgentExecutionTargetContext context, CancellationToken cancellationToken = default) => InvokeFacetAsync<AgentExecutionTargetContextWire, IReadOnlyList<string>>(AgentExecutionFacetIds.PathEnvironment, "list-path", AgentExecutionTargetContextWire.FromContext(context), cancellationToken);
    public async ValueTask AddPathEntryAsync(AgentExecutionTargetContext context, string executionPath, CancellationToken cancellationToken = default) => _ = await InvokeFacetAsync<ExecutionPathRequest, AgentRpcEmpty>(AgentExecutionFacetIds.PathEnvironment, "add-path", new(AgentExecutionTargetContextWire.FromContext(context), executionPath), cancellationToken).ConfigureAwait(false);
    public ValueTask<AgentFileSearchProcessResult> ExecuteFileSearchProcessAsync(AgentExecutionTargetContext context, AgentFileSearchProcessRequest request, CancellationToken cancellationToken = default) => InvokeFacetAsync<ExecutionFileSearchProcessRequest, AgentFileSearchProcessResult>(AgentExecutionFacetIds.LegacyFileSearch, "legacy-file-search", new(AgentExecutionTargetContextWire.FromContext(context), request), cancellationToken);
    public ValueTask<AgentFileSearchResult> ExecuteFileSearchAsync(AgentExecutionTargetContext context, AgentFileSearchRequest request, CancellationToken cancellationToken = default) => InvokeFacetAsync<ExecutionFileSearchRequest, AgentFileSearchResult>(AgentExecutionFacetIds.StructuredFileSearch, "structured-file-search", new(AgentExecutionTargetContextWire.FromContext(context), request), cancellationToken);
    public ValueTask<AgentScopedInstructionDiscoveryResult> DiscoverScopedInstructionsAsync(AgentExecutionTargetContext context, AgentScopedInstructionDiscoveryRequest request, CancellationToken cancellationToken = default) => InvokeFacetAsync<ExecutionInstructionDiscoveryRequest, AgentScopedInstructionDiscoveryResult>(AgentExecutionFacetIds.ScopedInstructionDiscovery, "discover-instructions", new(AgentExecutionTargetContextWire.FromContext(context), request), cancellationToken);

    private TResponse Invoke<TRequest, TResponse>(string method, TRequest request) where TRequest : notnull where TResponse : notnull => InvokeAsync<TRequest, TResponse>(method, request).AsTask().GetAwaiter().GetResult();
    private ValueTask<TResponse> InvokeAsync<TRequest, TResponse>(string method, TRequest request, CancellationToken token = default) where TRequest : notnull where TResponse : notnull => AgentRpcServiceHandler.InvokeAsync<TRequest, TResponse>(_client, _endpoint, AgentExecutionTargetRpc.ServiceId, method, request, token);
    private TResponse InvokeFacet<TRequest, TResponse>(string facet, string method, TRequest request) where TRequest : notnull where TResponse : notnull { RequireFacet(facet); return Invoke<TRequest, TResponse>(method, request); }
    private ValueTask<TResponse> InvokeFacetAsync<TRequest, TResponse>(string facet, string method, TRequest request, CancellationToken token) where TRequest : notnull where TResponse : notnull { RequireFacet(facet); return InvokeAsync<TRequest, TResponse>(method, request, token); }
    private void RequireFacet(string facet) { if (!Descriptor.SupportsFacet(facet)) throw new NotSupportedException($"Execution target facet '{facet}' is not advertised."); }
}

public sealed record AgentExecutionTargetContextWire(
    AgentExecutionTargetContext Context,
    IReadOnlyList<string> ApprovedResourceCapabilities,
    AgentResourceOperationContextWire? ResourceOperation,
    bool CapturePostMutationResource,
    string? ExpectedConfigurationGeneration)
{
    public static AgentExecutionTargetContextWire FromContext(AgentExecutionTargetContext context)
        => new(
            context,
            context.ApprovedResourceCapabilities,
            AgentResourceOperationContextWire.FromContext(context.ResourceOperation),
            context.CapturePostMutationResource,
            context.ExpectedConfigurationGeneration);

    public AgentExecutionTargetContext ToContext()
        => Context with
        {
            ApprovedResourceCapabilities = ApprovedResourceCapabilities,
            ResourceOperation = ResourceOperation?.ToContext(),
            CapturePostMutationResource = CapturePostMutationResource,
            ExpectedConfigurationGeneration = ExpectedConfigurationGeneration,
        };
}

public sealed record ExecutionPathRequest(AgentExecutionTargetContextWire Context, string Path);
public sealed record ExecutionShellRequest(AgentExecutionTargetContextWire Context, AgentShellCommandRequest Request);
public sealed record ExecutionFileReadRequest(AgentExecutionTargetContextWire Context, AgentFileReadRequest Request);
public sealed record ExecutionFileWriteRequest(AgentExecutionTargetContextWire Context, AgentFileWriteRequest Request);
public sealed record ExecutionFileDeleteRequest(AgentExecutionTargetContextWire Context, AgentFileDeleteRequest Request);
public sealed record ExecutionProcessRequest(AgentExecutionTargetContextWire Context, AgentProcessCommandRequest Request);
public sealed record ExecutionResourcesRequest(AgentExecutionTargetContextWire Context, IReadOnlyList<AgentExecutionResourceDescriptor> Resources);
public sealed record ResourceCapabilitiesRequest(IReadOnlyList<string> Capabilities);
public sealed record ExecutionFileSearchProcessRequest(AgentExecutionTargetContextWire Context, AgentFileSearchProcessRequest Request);
public sealed record ExecutionFileSearchRequest(AgentExecutionTargetContextWire Context, AgentFileSearchRequest Request);
public sealed record ExecutionInstructionDiscoveryRequest(AgentExecutionTargetContextWire Context, AgentScopedInstructionDiscoveryRequest Request);

public sealed record AgentResolvedResourceWire(
    AgentResolvedResource Resource,
    IReadOnlyList<string> AuthorityReferences,
    IReadOnlyList<string> DeleteAuthorityReferences)
{
    public static AgentResolvedResourceWire FromResource(AgentResolvedResource resource)
        => new(resource, resource.AuthorityReferences, resource.DeleteAuthorityReferences);

    public AgentResolvedResource ToResource()
        => Resource with
        {
            AuthorityReferences = AuthorityReferences,
            DeleteAuthorityReferences = DeleteAuthorityReferences,
        };
}

public sealed record AgentFileMutationResultWire(
    AgentFileMutationResult Result,
    AgentResolvedResourceWire? PostMutationResource)
{
    public static AgentFileMutationResultWire FromResult(AgentFileMutationResult result)
        => new(
            result,
            result.PostMutationResource is null
                ? null
                : AgentResolvedResourceWire.FromResource(result.PostMutationResource));

    public AgentFileMutationResult ToResult()
        => Result with { PostMutationResource = PostMutationResource?.ToResource() };
}
