// <auto-generated />
using Sunder.Package.Agent.Contracts.Contracts;
using Sunder.Package.Agent.Contracts.Models;
using Sunder.Sdk.Rpc;

namespace Sunder.Package.Agent.Protocol;

public static class AgentWorkspaceExecutionResolverRpc
{
    private const int MaximumListPayloadCharacters = 900_000;
    public const string ServiceId = "workspace-execution-resolver";

    public static ISunderRpcServiceHandler CreateHandler(IAgentWorkspaceExecutionResolver resolver)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, IReadOnlyList<AgentWorkspaceRecord>>(ServiceId, "list-workspaces", (_, _, _) => ValueTask.FromResult(BoundWorkspaceList(resolver.ListWorkspaces())))
            .AddUnary<StringRequest, AgentWorkspaceExecutionResolutionWire>(ServiceId, "resolve", async (_, request, token) =>
            {
                var resolution = await resolver.ResolveAsync(request.Value, token).ConfigureAwait(false);
                var handle = resolution.ExecutionTargetHandle ?? resolution.ExecutionTargetReference?.ToHandle()
                    ?? throw new InvalidOperationException("Workspace execution resolution did not retain an exact RPC target handle.");
                return new AgentWorkspaceExecutionResolutionWire(
                    resolution.Workspace,
                    resolution.Binding,
                    resolution.Target,
                    resolution.Scope,
                    handle);
            })
            .Build();

    private static IReadOnlyList<AgentWorkspaceRecord> BoundWorkspaceList(IReadOnlyList<AgentWorkspaceRecord> workspaces)
    {
        var result = new List<AgentWorkspaceRecord>();
        foreach (var workspace in workspaces)
        {
            result.Add(workspace);
            if (AgentRpcServiceHandler.Serialize(result).Length <= MaximumListPayloadCharacters)
            {
                continue;
            }
            result.RemoveAt(result.Count - 1);
            break;
        }
        return result;
    }
}

public sealed class AgentWorkspaceExecutionResolverRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentWorkspaceExecutionResolver
{
    public IReadOnlyList<AgentWorkspaceRecord> ListWorkspaces()
        => AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, IReadOnlyList<AgentWorkspaceRecord>>(client, endpoint, AgentWorkspaceExecutionResolverRpc.ServiceId, "list-workspaces", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();

    public async ValueTask<AgentWorkspaceExecutionResolution> ResolveAsync(string workspaceId, CancellationToken cancellationToken = default)
    {
        var wire = await AgentRpcServiceHandler.InvokeAsync<StringRequest, AgentWorkspaceExecutionResolutionWire>(client, endpoint, AgentWorkspaceExecutionResolverRpc.ServiceId, "resolve", new(workspaceId), cancellationToken).ConfigureAwait(false);
        var targetEndpoint = new SunderRpcEndpointReference(wire.ExecutionTarget.EndpointReference);
        var provider = await client.GetProviderAsync(targetEndpoint, cancellationToken).ConfigureAwait(false)
                       ?? throw new SunderRpcException(new SunderRpcError(SunderRpcErrorKind.StaleEndpoint, "agent.execution.target-stale", "The resolved execution target activation is stale."));
        if (!wire.ExecutionTarget.Matches(provider))
        {
            throw new SunderRpcException(new SunderRpcError(SunderRpcErrorKind.StaleEndpoint, "agent.execution.target-replaced", "The resolved execution target activation was replaced."));
        }
        var reference = new AgentRpcReference<IAgentExecutionTarget>(client, AgentRpcServices.ExecutionTargets, provider);
        var target = new AgentExecutionTargetRpcClient(client, targetEndpoint);
        return new AgentWorkspaceExecutionResolution(wire.Workspace, wire.Binding, target.Descriptor, wire.Scope, target)
        {
            ExecutionTargetHandle = wire.ExecutionTarget,
            ExecutionTargetReference = reference,
        };
    }
}

public sealed record AgentWorkspaceExecutionResolutionWire(
    AgentWorkspaceRecord Workspace,
    AgentWorkspaceBindingRecord Binding,
    AgentExecutionTargetDescriptor Target,
    AgentExecutionScopeDescriptor Scope,
    AgentRpcProviderHandle ExecutionTarget);
