// <auto-generated />
using System.Runtime.CompilerServices;
using System.Threading.Channels;
using Sunder.Package.Agent.Contracts.Contracts;
using Sunder.Package.Agent.Contracts.Models;
using Sunder.Sdk.Rpc;

namespace Sunder.Package.Agent.Protocol;

public static class AgentRuntimeCatalogRpc
{
    public const string ServiceId = "runtime-catalog";

    public static ISunderRpcServiceHandler CreateHandler(IAgentRuntimeCatalog catalog)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, IReadOnlyList<AgentSessionRecord>>(ServiceId, "list-sessions", (_, _, _) => ValueTask.FromResult(catalog.ListSessions()))
            .AddUnary<StringRequest, IReadOnlyList<AgentSessionRecord>>(ServiceId, "list-sessions-for-profile", (_, request, _) => ValueTask.FromResult(catalog.ListSessionsForProfile(request.Value)))
            .AddUnary<StringRequest, IReadOnlyList<AgentSessionRecord>>(ServiceId, "list-sessions-for-workspace", (_, request, _) => ValueTask.FromResult(catalog.ListSessionsForWorkspace(request.Value)))
            .AddUnary<SessionIdRequest, AgentRpcOptional<AgentSessionRecord>>(ServiceId, "get-session", (_, request, _) => ValueTask.FromResult(new AgentRpcOptional<AgentSessionRecord>(true, catalog.GetSession(request.SessionId))))
            .AddUnary<AgentRpcEmpty, IReadOnlyList<AgentWorkspaceRecord>>(ServiceId, "list-workspaces", (_, _, _) => ValueTask.FromResult(catalog.ListWorkspaces()))
            .AddUnary<StringRequest, AgentRpcOptional<AgentWorkspaceRecord>>(ServiceId, "get-workspace", (_, request, _) => ValueTask.FromResult(new AgentRpcOptional<AgentWorkspaceRecord>(true, catalog.GetWorkspace(request.Value))))
            .AddUnary<SessionIdRequest, AgentRpcOptional<AgentProfileRecord>>(ServiceId, "get-session-profile", (_, request, _) => ValueTask.FromResult(new AgentRpcOptional<AgentProfileRecord>(true, catalog.GetSessionProfile(request.SessionId))))
            .AddUnary<SessionIdRequest, AgentRpcOptional<AgentWorkingSummaryRecord>>(ServiceId, "get-working-summary", (_, request, _) => ValueTask.FromResult(new AgentRpcOptional<AgentWorkingSummaryRecord>(true, catalog.GetWorkingSummary(request.SessionId))))
            .AddUnary<SessionIdRequest, AgentRpcOptional<AgentSessionContextCheckpointRecord>>(ServiceId, "get-session-context-checkpoint", (_, request, _) => ValueTask.FromResult(new AgentRpcOptional<AgentSessionContextCheckpointRecord>(true, catalog.GetLatestSessionContextCheckpoint(request.SessionId))))
            .AddUnary<SessionIdRequest, AgentRpcOptional<AgentRunCheckpointRecord>>(ServiceId, "get-latest-checkpoint", (_, request, _) => ValueTask.FromResult(new AgentRpcOptional<AgentRunCheckpointRecord>(true, catalog.GetLatestCheckpoint(request.SessionId))))
            .AddUnary<RecentTurnsRequest, IReadOnlyList<AgentTurnRecord>>(ServiceId, "list-recent-turns", (_, request, _) => ValueTask.FromResult(catalog.ListRecentTurns(request.SessionId, request.Limit)))
            .AddUnary<TurnBoundaryRequest, IReadOnlyList<AgentTurnRecord>>(ServiceId, "list-turns-before", (_, request, _) => ValueTask.FromResult(catalog.ListTurnsBefore(request.SessionId, request.CreatedAtUtc, request.TurnId, request.Limit)))
            .AddUnary<TurnBoundaryRequest, IReadOnlyList<AgentTurnRecord>>(ServiceId, "list-turns-after", (_, request, _) => ValueTask.FromResult(catalog.ListTurnsAfter(request.SessionId, request.CreatedAtUtc, request.TurnId, request.Limit)))
            .AddUnary<RecentTurnsRequest, IReadOnlyList<AgentTurnRecord>>(ServiceId, "list-recent-transcript-headers", (_, request, _) => ValueTask.FromResult(
                catalog is IAgentTranscriptCatalog transcript
                    ? transcript.ListRecentTranscriptHeaders(request.SessionId, request.Limit)
                    : catalog.ListRecentTurns(request.SessionId, request.Limit)))
            .AddUnary<TurnBoundaryRequest, IReadOnlyList<AgentTurnRecord>>(ServiceId, "list-transcript-headers-before", (_, request, _) => ValueTask.FromResult(
                catalog is IAgentTranscriptCatalog transcript
                    ? transcript.ListTranscriptHeadersBefore(request.SessionId, request.CreatedAtUtc, request.TurnId, request.Limit)
                    : catalog.ListTurnsBefore(request.SessionId, request.CreatedAtUtc, request.TurnId, request.Limit)))
            .AddUnary<TurnBoundaryRequest, IReadOnlyList<AgentTurnRecord>>(ServiceId, "list-transcript-headers-after", (_, request, _) => ValueTask.FromResult(
                catalog is IAgentTranscriptCatalog transcript
                    ? transcript.ListTranscriptHeadersAfter(request.SessionId, request.CreatedAtUtc, request.TurnId, request.Limit)
                    : catalog.ListTurnsAfter(request.SessionId, request.CreatedAtUtc, request.TurnId, request.Limit)))
            .AddUnary<AgentTranscriptToolDetailRequest, AgentRpcOptional<AgentTranscriptToolDetailRecord>>(ServiceId, "get-transcript-tool-detail", (_, request, _) => ValueTask.FromResult(
                new AgentRpcOptional<AgentTranscriptToolDetailRecord>(true, (catalog as IAgentTranscriptCatalog)?.GetTranscriptToolDetail(request))))
            .AddUnary<AgentRpcEmpty, IReadOnlyList<AgentProfileRecord>>(ServiceId, "list-profiles", (_, _, _) => ValueTask.FromResult(catalog.ListProfiles()))
            .AddUnary<StringRequest, AgentRpcOptional<AgentProfileRecord>>(ServiceId, "get-profile", (_, request, _) => ValueTask.FromResult(new AgentRpcOptional<AgentProfileRecord>(true, catalog.GetProfile(request.Value))))
            .AddUnary<SessionCapabilityRequest, AgentRpcOptional<AgentProfileModelBindingRecord>>(ServiceId, "get-session-model-binding", (_, request, _) => ValueTask.FromResult(new AgentRpcOptional<AgentProfileModelBindingRecord>(true, catalog.GetSessionModelBinding(request.SessionId, request.CapabilityKind))))
            .AddUnary<ProfileCapabilityRequest, AgentRpcOptional<AgentProfileModelBindingRecord>>(ServiceId, "get-model-binding", (_, request, _) => ValueTask.FromResult(new AgentRpcOptional<AgentProfileModelBindingRecord>(true, catalog.GetModelBinding(request.ProfileId, request.CapabilityKind))))
            .AddStream<AgentRpcEmpty, AgentRuntimeCatalogEvent>(ServiceId, "watch", (_, _, token) => WatchAsync(catalog, token))
            .Build();

    private static async IAsyncEnumerable<AgentRuntimeCatalogEvent> WatchAsync(
        IAgentRuntimeCatalog catalog,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        var channel = Channel.CreateBounded<AgentRuntimeCatalogEvent>(new BoundedChannelOptions(256)
        {
            FullMode = BoundedChannelFullMode.DropOldest,
            SingleReader = true,
            SingleWriter = false,
        });
        long sequence = 0;
        void Session(Guid id) => channel.Writer.TryWrite(new("session", Interlocked.Increment(ref sequence), id));
        void Turn(Guid id, AgentTurnRecord turn) => channel.Writer.TryWrite(new("turn", Interlocked.Increment(ref sequence), id, Turn: turn));
        void Profile(string id) => channel.Writer.TryWrite(new("profile", Interlocked.Increment(ref sequence), ProfileId: id));
        catalog.SessionChanged += Session;
        catalog.TurnChanged += Turn;
        catalog.ProfileChanged += Profile;
        try
        {
            await foreach (var item in channel.Reader.ReadAllAsync(cancellationToken).ConfigureAwait(false)) yield return item;
        }
        finally
        {
            catalog.SessionChanged -= Session;
            catalog.TurnChanged -= Turn;
            catalog.ProfileChanged -= Profile;
            channel.Writer.TryComplete();
        }
    }
}

public sealed class AgentRuntimeCatalogRpcClient : IAgentRuntimeCatalog, IAgentTranscriptCatalog, IDisposable
{
    private readonly ISunderRpcClient _client;
    private readonly SunderRpcEndpointReference _endpoint;
    private readonly CancellationTokenSource _lifetime = new();
    private readonly Task _watch;

    public AgentRuntimeCatalogRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint)
    {
        _client = client;
        _endpoint = endpoint;
        _watch = WatchAsync();
    }

    public event Action<Guid>? SessionChanged;
    public event Action<Guid, AgentTurnRecord>? TurnChanged;
    public event Action<string>? ProfileChanged;

    public IReadOnlyList<AgentSessionRecord> ListSessions() => Invoke<AgentRpcEmpty, IReadOnlyList<AgentSessionRecord>>("list-sessions", new AgentRpcEmpty());
    public IReadOnlyList<AgentSessionRecord> ListSessionsForProfile(string profileId) => Invoke<StringRequest, IReadOnlyList<AgentSessionRecord>>("list-sessions-for-profile", new(profileId));
    public IReadOnlyList<AgentSessionRecord> ListSessionsForWorkspace(string workspaceId) => Invoke<StringRequest, IReadOnlyList<AgentSessionRecord>>("list-sessions-for-workspace", new(workspaceId));
    public AgentSessionRecord? GetSession(Guid sessionId) => Invoke<SessionIdRequest, AgentRpcOptional<AgentSessionRecord>>("get-session", new(sessionId)).Value;
    public IReadOnlyList<AgentWorkspaceRecord> ListWorkspaces() => Invoke<AgentRpcEmpty, IReadOnlyList<AgentWorkspaceRecord>>("list-workspaces", new AgentRpcEmpty());
    public AgentWorkspaceRecord? GetWorkspace(string workspaceId) => Invoke<StringRequest, AgentRpcOptional<AgentWorkspaceRecord>>("get-workspace", new(workspaceId)).Value;
    public AgentProfileRecord? GetSessionProfile(Guid sessionId) => Invoke<SessionIdRequest, AgentRpcOptional<AgentProfileRecord>>("get-session-profile", new(sessionId)).Value;
    public AgentWorkingSummaryRecord? GetWorkingSummary(Guid sessionId) => Invoke<SessionIdRequest, AgentRpcOptional<AgentWorkingSummaryRecord>>("get-working-summary", new(sessionId)).Value;
    public AgentSessionContextCheckpointRecord? GetLatestSessionContextCheckpoint(Guid sessionId) => Invoke<SessionIdRequest, AgentRpcOptional<AgentSessionContextCheckpointRecord>>("get-session-context-checkpoint", new(sessionId)).Value;
    public AgentRunCheckpointRecord? GetLatestCheckpoint(Guid sessionId) => Invoke<SessionIdRequest, AgentRpcOptional<AgentRunCheckpointRecord>>("get-latest-checkpoint", new(sessionId)).Value;
    public IReadOnlyList<AgentTurnRecord> ListRecentTurns(Guid sessionId, int limit) => Invoke<RecentTurnsRequest, IReadOnlyList<AgentTurnRecord>>("list-recent-turns", new(sessionId, limit));
    public IReadOnlyList<AgentTurnRecord> ListTurnsBefore(Guid sessionId, DateTimeOffset beforeCreatedAtUtc, Guid beforeTurnId, int limit) => Invoke<TurnBoundaryRequest, IReadOnlyList<AgentTurnRecord>>("list-turns-before", new(sessionId, beforeCreatedAtUtc, beforeTurnId, limit));
    public IReadOnlyList<AgentTurnRecord> ListTurnsAfter(Guid sessionId, DateTimeOffset afterCreatedAtUtc, Guid afterTurnId, int limit) => Invoke<TurnBoundaryRequest, IReadOnlyList<AgentTurnRecord>>("list-turns-after", new(sessionId, afterCreatedAtUtc, afterTurnId, limit));
    public IReadOnlyList<AgentTurnRecord> ListRecentTranscriptHeaders(Guid sessionId, int limit) => Invoke<RecentTurnsRequest, IReadOnlyList<AgentTurnRecord>>("list-recent-transcript-headers", new(sessionId, limit));
    public IReadOnlyList<AgentTurnRecord> ListTranscriptHeadersBefore(Guid sessionId, DateTimeOffset beforeCreatedAtUtc, Guid beforeTurnId, int limit) => Invoke<TurnBoundaryRequest, IReadOnlyList<AgentTurnRecord>>("list-transcript-headers-before", new(sessionId, beforeCreatedAtUtc, beforeTurnId, limit));
    public IReadOnlyList<AgentTurnRecord> ListTranscriptHeadersAfter(Guid sessionId, DateTimeOffset afterCreatedAtUtc, Guid afterTurnId, int limit) => Invoke<TurnBoundaryRequest, IReadOnlyList<AgentTurnRecord>>("list-transcript-headers-after", new(sessionId, afterCreatedAtUtc, afterTurnId, limit));
    public AgentTranscriptToolDetailRecord? GetTranscriptToolDetail(AgentTranscriptToolDetailRequest request) => Invoke<AgentTranscriptToolDetailRequest, AgentRpcOptional<AgentTranscriptToolDetailRecord>>("get-transcript-tool-detail", request).Value;
    public IReadOnlyList<AgentProfileRecord> ListProfiles() => Invoke<AgentRpcEmpty, IReadOnlyList<AgentProfileRecord>>("list-profiles", new AgentRpcEmpty());
    public AgentProfileRecord? GetProfile(string profileId) => Invoke<StringRequest, AgentRpcOptional<AgentProfileRecord>>("get-profile", new(profileId)).Value;
    public AgentProfileModelBindingRecord? GetSessionModelBinding(Guid sessionId, string capabilityKind) => Invoke<SessionCapabilityRequest, AgentRpcOptional<AgentProfileModelBindingRecord>>("get-session-model-binding", new(sessionId, capabilityKind)).Value;
    public AgentProfileModelBindingRecord? GetModelBinding(string profileId, string capabilityKind) => Invoke<ProfileCapabilityRequest, AgentRpcOptional<AgentProfileModelBindingRecord>>("get-model-binding", new(profileId, capabilityKind)).Value;

    public void Dispose()
    {
        _lifetime.Cancel();
        _ = _watch.ContinueWith(static (_, state) => ((CancellationTokenSource)state!).Dispose(), _lifetime, TaskScheduler.Default);
    }

    private TResponse Invoke<TRequest, TResponse>(string methodId, TRequest request) where TRequest : notnull where TResponse : notnull
        => AgentRpcServiceHandler.InvokeAsync<TRequest, TResponse>(_client, _endpoint, AgentRuntimeCatalogRpc.ServiceId, methodId, request, _lifetime.Token).AsTask().GetAwaiter().GetResult();

    private async Task WatchAsync()
    {
        try
        {
            await foreach (var item in AgentRpcServiceHandler.SubscribeAsync<AgentRpcEmpty, AgentRuntimeCatalogEvent>(_client, _endpoint, AgentRuntimeCatalogRpc.ServiceId, "watch", new AgentRpcEmpty(), _lifetime.Token).ConfigureAwait(false))
            {
                if (item.Kind == "session" && item.SessionId is { } sessionId) SessionChanged?.Invoke(sessionId);
                else if (item.Kind == "turn" && item.SessionId is { } turnSessionId && item.Turn is not null) TurnChanged?.Invoke(turnSessionId, item.Turn);
                else if (item.Kind == "profile" && item.ProfileId is not null) ProfileChanged?.Invoke(item.ProfileId);
            }
        }
        catch (Exception exception) when (exception is OperationCanceledException or SunderRpcException)
        {
        }
    }
}

public sealed record AgentRuntimeCatalogEvent(string Kind, long Sequence, Guid? SessionId = null, string? ProfileId = null, AgentTurnRecord? Turn = null);
public sealed record StringRequest(string Value);
public sealed record RecentTurnsRequest(Guid SessionId, int Limit);
public sealed record TurnBoundaryRequest(Guid SessionId, DateTimeOffset CreatedAtUtc, Guid TurnId, int Limit);
public sealed record SessionCapabilityRequest(Guid SessionId, string CapabilityKind);
public sealed record ProfileCapabilityRequest(string ProfileId, string CapabilityKind);
