// <auto-generated />
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Channels;
using Microsoft.Extensions.AI;
using Sunder.Package.Agent.Contracts.Contracts;
using Sunder.Package.Agent.Contracts.Models;
using Sunder.Sdk.Rpc;

namespace Sunder.Package.Agent.Protocol;

#pragma warning disable MEAI001

public static class AgentChatProviderRpc
{
    public const string ServiceId = "chat-provider";

    public static ISunderRpcServiceHandler CreateHandler(IAgentChatProvider provider)
    {
        return AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentProviderDescriptor>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(provider.Descriptor))
            .AddUnary<AgentRpcEmpty, IReadOnlyList<AgentModelDescriptor>>(ServiceId, "list-models", (_, _, token) => provider.GetAvailableModelsAsync(token))
            .AddUnary<AgentRpcEmpty, AgentProviderReadiness>(ServiceId, "get-readiness", (_, _, token) => provider.GetReadinessAsync(token))
            .AddUnary<ChatCapabilitiesRequest, AgentProviderRunCapabilities>(ServiceId, "get-capabilities", (_, request, token) => provider.GetRunCapabilitiesAsync(request.ModelId, token))
            .AddUnary<AgentRpcEmpty, AgentRpcOptional<string>>(ServiceId, "resolve-utility-model", async (_, _, token) =>
                new AgentRpcOptional<string>(
                    true,
                    provider is IAgentUtilityModelProvider utility
                        ? await utility.ResolveUtilityModelIdAsync(token).ConfigureAwait(false)
                        : null))
            .AddStream<AgentChatStreamRequest, AgentChatStreamEvent>(ServiceId, "stream-chat", (context, request, token) =>
                StreamAsync(provider, request, context, token))
            .Build();
    }

    private static async IAsyncEnumerable<AgentChatStreamEvent> StreamAsync(
        IAgentChatProvider provider,
        AgentChatStreamRequest request,
        SunderRpcInvocationContext context,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        var channel = Channel.CreateBounded<AgentChatStreamEvent>(new BoundedChannelOptions(64)
        {
            FullMode = BoundedChannelFullMode.Wait,
            SingleReader = true,
            SingleWriter = true,
        });
        var producer = ProduceAsync(
            provider,
            request,
            context,
            channel.Writer,
            cancellationToken);
        await foreach (var item in channel.Reader.ReadAllAsync(cancellationToken).ConfigureAwait(false))
        {
            yield return item;
        }
        await producer.ConfigureAwait(false);
    }

    private static async Task ProduceAsync(
        IAgentChatProvider provider,
        AgentChatStreamRequest request,
        SunderRpcInvocationContext context,
        ChannelWriter<AgentChatStreamEvent> writer,
        CancellationToken cancellationToken)
    {
        IChatClient? chatClient = null;
        try
        {
            chatClient = await provider.CreateChatClientAsync(
                new AgentChatClientContext(request.ProviderId, request.ModelId),
                cancellationToken).ConfigureAwait(false);
            var messages = await AgentChatWireMapper.ToChatMessagesAsync(
                request.Messages,
                context,
                cancellationToken).ConfigureAwait(false);
            await foreach (var update in chatClient.GetStreamingResponseAsync(
                               messages,
                               AgentChatWireMapper.ToChatOptions(request.Options),
                               cancellationToken).WithCancellation(cancellationToken).ConfigureAwait(false))
            {
                await writer.WriteAsync(AgentChatWireMapper.FromUpdate(update), cancellationToken).ConfigureAwait(false);
            }
        }
        catch (AgentChatProviderException exception)
        {
            await writer.WriteAsync(AgentChatStreamEvent.Error(
                exception.ErrorCode ?? "provider-error",
                exception.Message,
                exception.Content,
                exception.FailureKind.ToString()), cancellationToken).ConfigureAwait(false);
        }
        finally
        {
            chatClient?.Dispose();
            writer.TryComplete();
        }
    }
}

public sealed class AgentChatProviderRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentChatProvider, IAgentUtilityModelProvider
{
    private AgentProviderDescriptor? _descriptor;

    public AgentProviderDescriptor Descriptor
        => _descriptor ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentProviderDescriptor>(client, endpoint, AgentChatProviderRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();

    public ValueTask<IReadOnlyList<AgentModelDescriptor>> GetAvailableModelsAsync(CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, IReadOnlyList<AgentModelDescriptor>>(client, endpoint, AgentChatProviderRpc.ServiceId, "list-models", new AgentRpcEmpty(), cancellationToken);

    public ValueTask<AgentProviderReadiness> GetReadinessAsync(CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentProviderReadiness>(client, endpoint, AgentChatProviderRpc.ServiceId, "get-readiness", new AgentRpcEmpty(), cancellationToken);

    public ValueTask<AgentProviderRunCapabilities> GetRunCapabilitiesAsync(string? modelId, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<ChatCapabilitiesRequest, AgentProviderRunCapabilities>(client, endpoint, AgentChatProviderRpc.ServiceId, "get-capabilities", new(modelId), cancellationToken);

    public async ValueTask<string?> ResolveUtilityModelIdAsync(CancellationToken cancellationToken = default)
        => (await AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentRpcOptional<string>>(
            client,
            endpoint,
            AgentChatProviderRpc.ServiceId,
            "resolve-utility-model",
            new AgentRpcEmpty(),
            cancellationToken).ConfigureAwait(false)).Value;

    public ValueTask<IChatClient> CreateChatClientAsync(AgentChatClientContext context, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        return ValueTask.FromResult<IChatClient>(new AgentRpcChatClient(client, endpoint, context.ProviderId, context.ModelId));
    }
}

internal sealed class AgentRpcChatClient(
    ISunderRpcClient client,
    SunderRpcEndpointReference endpoint,
    string providerId,
    string modelId) : IChatClient
{
    public async Task<ChatResponse> GetResponseAsync(
        IEnumerable<ChatMessage> messages,
        ChatOptions? options = null,
        CancellationToken cancellationToken = default)
        => await GetStreamingResponseAsync(messages, options, cancellationToken)
            .ToChatResponseAsync(cancellationToken).ConfigureAwait(false);

    public async IAsyncEnumerable<ChatResponseUpdate> GetStreamingResponseAsync(
        IEnumerable<ChatMessage> messages,
        ChatOptions? options = null,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        ISunderRpcCallScope? scope = null;
        try
        {
            var mappedMessages = await AgentChatWireMapper.FromChatMessagesAsync(
                messages,
                RegisterContentAsync,
                cancellationToken).ConfigureAwait(false);
            var request = new AgentChatStreamRequest(
                providerId,
                modelId,
                mappedMessages,
                AgentChatWireMapper.FromChatOptions(options));
            ISunderRpcClient invocationClient = scope is null ? client : scope;
            await foreach (var item in AgentRpcServiceHandler.SubscribeAsync<AgentChatStreamRequest, AgentChatStreamEvent>(
                               invocationClient,
                               endpoint,
                               AgentChatProviderRpc.ServiceId,
                               "stream-chat",
                               request,
                               cancellationToken).WithCancellation(cancellationToken).ConfigureAwait(false))
            {
                if (item.Kind == AgentChatStreamEvent.ErrorKind)
                {
                    throw new AgentChatProviderException(
                        item.ErrorMessage ?? "Provider request failed.",
                        item.ErrorContent ?? item.ErrorMessage ?? "Provider request failed.",
                        item.ErrorCode)
                    {
                        FailureKind = Enum.TryParse<AgentChatProviderFailureKind>(item.ErrorFailureKind, out var kind)
                            ? kind
                            : AgentChatProviderFailureKind.Unknown,
                    };
                }
                yield return AgentChatWireMapper.ToUpdate(item);
            }
        }
        finally
        {
            if (scope is not null)
            {
                await scope.DisposeAsync().ConfigureAwait(false);
            }
        }

        async ValueTask<SunderRpcContentReference> RegisterContentAsync(
            DataContent content,
            CancellationToken token)
        {
            scope ??= await client.CreateCallScopeAsync(cancellationToken: token).ConfigureAwait(false);
            return await AgentChatWireMapper.RegisterContentAsync(
                scope,
                endpoint,
                content,
                token).ConfigureAwait(false);
        }
    }

    public object? GetService(Type serviceType, object? serviceKey = null) => null;

    public void Dispose()
    {
    }
}

internal static class AgentChatWireMapper
{
    internal const int MaxContentBytes = 32 * 1024 * 1024;

    public static async ValueTask<IReadOnlyList<AgentChatMessage>> FromChatMessagesAsync(
        IEnumerable<ChatMessage> messages,
        Func<DataContent, CancellationToken, ValueTask<SunderRpcContentReference>> registerContentAsync,
        CancellationToken cancellationToken)
    {
        var mappedMessages = new List<AgentChatMessage>();
        foreach (var message in messages)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var mappedContents = new List<AgentChatContent>(message.Contents.Count);
            foreach (var content in message.Contents)
            {
                if (content is DataContent data && !data.Data.IsEmpty)
                {
                    var reference = await registerContentAsync(data, cancellationToken).ConfigureAwait(false);
                    mappedContents.Add(FromContentReference(data, reference));
                }
                else
                {
                    mappedContents.Add(FromContent(content));
                }
            }
            mappedMessages.Add(FromChatMessage(message, mappedContents));
        }
        return mappedMessages;
    }

    public static async ValueTask<SunderRpcContentReference> RegisterContentAsync(
        ISunderRpcCallScope scope,
        SunderRpcEndpointReference endpoint,
        DataContent content,
        CancellationToken cancellationToken)
    {
        if (content.Data.Length > MaxContentBytes)
        {
            throw new SunderRpcException(new SunderRpcError(
                SunderRpcErrorKind.ResourceExhausted,
                "rpc.content.length-limit",
                "Chat binary content exceeds the transfer limit."));
        }

        await using var source = new MemoryStream(content.Data.ToArray(), writable: false);
        return await scope.RegisterContentAsync(
            endpoint,
            source,
            new SunderRpcContentRegistrationOptions(
                content.MediaType,
                string.IsNullOrWhiteSpace(content.Name) ? "content.bin" : content.Name,
                content.Data.Length,
                Repeatability: SunderRpcContentRepeatability.SingleUse,
                MaximumUses: 1),
            cancellationToken).ConfigureAwait(false);
    }

    public static async ValueTask<IReadOnlyList<ChatMessage>> ToChatMessagesAsync(
        IReadOnlyList<AgentChatMessage> messages,
        SunderRpcInvocationContext context,
        CancellationToken cancellationToken)
    {
        var contentByReference = new Dictionary<SunderRpcContentReference, ReadOnlyMemory<byte>>();
        foreach (var reference in messages
                     .SelectMany(static message => message.Contents)
                     .Select(static content => content.ContentReference)
                     .Where(static reference => reference is not null)
                     .Cast<SunderRpcContentReference>()
                     .Distinct())
        {
            if (reference.Length is < 0 or > MaxContentBytes)
            {
                throw new InvalidDataException("Chat binary content exceeds the transfer limit.");
            }

            await using var source = await context.OpenContentAsync(reference, cancellationToken).ConfigureAwait(false);
            var bytes = new byte[checked((int)reference.Length)];
            await source.ReadExactlyAsync(bytes, cancellationToken).ConfigureAwait(false);
            contentByReference.Add(reference, bytes);
        }

        return messages
            .Select(message => ToChatMessage(message, reference => contentByReference[reference]))
            .ToArray();
    }

    public static AgentChatMessage FromChatMessage(ChatMessage message)
        => FromChatMessage(message, message.Contents.Select(FromContent).ToArray());

    public static AgentChatMessage FromChatMessage(
        ChatMessage message,
        IReadOnlyList<AgentChatContent> contents)
        => new(
            message.Role.Value,
            message.MessageId,
            message.AuthorName,
            contents);

    public static ChatMessage ToChatMessage(
        AgentChatMessage message,
        Func<SunderRpcContentReference, ReadOnlyMemory<byte>>? resolveContent = null)
        => new(new ChatRole(message.Role), message.Contents.Select(content => ToContent(content, resolveContent)).ToList())
        {
            MessageId = message.MessageId,
            AuthorName = message.AuthorName,
        };

    public static AgentChatOptions FromChatOptions(ChatOptions? options)
    {
        options ??= new ChatOptions();
        return new AgentChatOptions(
            options.Instructions,
            options.ConversationId,
            options.ModelId,
            options.Temperature,
            options.MaxOutputTokens,
            options.TopP,
            options.TopK,
            options.FrequencyPenalty,
            options.PresencePenalty,
            options.Seed,
            options.AllowMultipleToolCalls,
            options.Reasoning?.Effort.ToString(),
            options.Tools?.OfType<AIFunctionDeclaration>().Select(static tool => new AgentChatTool(
                tool.Name,
                tool.Description,
                tool.JsonSchema.GetRawText())).ToArray() ?? [],
            options.AdditionalProperties?.ToDictionary(
                static pair => pair.Key,
                static pair => JsonSerializer.Serialize(pair.Value),
                StringComparer.Ordinal),
            options.ContinuationToken is null
                ? null
                : Convert.ToBase64String(options.ContinuationToken.ToBytes().Span));
    }

    public static ChatOptions ToChatOptions(AgentChatOptions options)
    {
        var mapped = new ChatOptions
        {
            Instructions = options.Instructions,
            ConversationId = options.ConversationId,
            ModelId = options.ModelId,
            Temperature = options.Temperature,
            MaxOutputTokens = options.MaxOutputTokens,
            TopP = options.TopP,
            TopK = options.TopK,
            FrequencyPenalty = options.FrequencyPenalty,
            PresencePenalty = options.PresencePenalty,
            Seed = options.Seed,
            AllowMultipleToolCalls = options.AllowMultipleToolCalls,
            Tools = options.Tools.Select(static tool => (AITool)AIFunctionFactory.CreateDeclaration(
                tool.Name,
                tool.Description,
                JsonDocument.Parse(tool.JsonSchema).RootElement.Clone())).ToList(),
        };
        if (Enum.TryParse<ReasoningEffort>(options.ReasoningEffort, out var effort))
        {
            mapped.Reasoning = new ReasoningOptions { Effort = effort, Output = effort == ReasoningEffort.None ? ReasoningOutput.None : ReasoningOutput.Summary };
        }
        if (options.AdditionalProperties is { Count: > 0 })
        {
            mapped.AdditionalProperties = new AdditionalPropertiesDictionary();
            foreach (var pair in options.AdditionalProperties)
            {
                mapped.AdditionalProperties[pair.Key] = DeserializeAdditionalProperty(pair.Value);
            }
        }
        if (!string.IsNullOrWhiteSpace(options.ContinuationHandle))
        {
            mapped.ContinuationToken = ResponseContinuationToken.FromBytes(Convert.FromBase64String(options.ContinuationHandle));
        }
        return mapped;
    }

    public static AgentChatStreamEvent FromUpdate(ChatResponseUpdate update)
        => new(
            AgentChatStreamEvent.UpdateKind,
            update.Role?.Value,
            update.ResponseId,
            update.MessageId,
            update.ConversationId,
            update.ModelId,
            update.FinishReason?.Value,
            update.CreatedAt,
            update.Contents.Select(FromContent).ToArray(),
            update.ContinuationToken is null ? null : Convert.ToBase64String(update.ContinuationToken.ToBytes().Span));

    public static ChatResponseUpdate ToUpdate(AgentChatStreamEvent item)
        => new(
            item.Role is null ? null : new ChatRole(item.Role),
            item.Contents.Select(static content => ToContent(content, resolveContent: null)).ToList())
        {
            ResponseId = item.ResponseId,
            MessageId = item.MessageId,
            ConversationId = item.ConversationId,
            ModelId = item.ModelId,
            FinishReason = item.FinishReason is null ? null : new ChatFinishReason(item.FinishReason),
            CreatedAt = item.CreatedAt,
            ContinuationToken = item.ContinuationHandle is null
                ? null
                : ResponseContinuationToken.FromBytes(Convert.FromBase64String(item.ContinuationHandle)),
        };

    public static AgentChatContent FromContent(AIContent content)
        => content switch
        {
            TextReasoningContent reasoning => new("reasoning", Text: reasoning.Text, ProtectedData: reasoning.ProtectedData),
            TextContent text => new("text", Text: text.Text),
            FunctionCallContent call => new("tool-call", CallId: call.CallId, Name: call.Name, Json: JsonSerializer.Serialize(call.Arguments), InformationalOnly: call.InformationalOnly),
            FunctionResultContent result => new("tool-result", CallId: result.CallId, Json: JsonSerializer.Serialize(result.Result)),
            UsageContent usage => new("usage", Usage: new AgentChatUsage(
                usage.Details.InputTokenCount,
                usage.Details.OutputTokenCount,
                usage.Details.TotalTokenCount,
                usage.Details.CachedInputTokenCount,
                usage.Details.ReasoningTokenCount)),
            ErrorContent error => new("error", ErrorCode: error.ErrorCode, ErrorMessage: error.Message, Json: JsonSerializer.Serialize(error.Details)),
            DataContent data => new("content-reference", Name: data.Name, MediaType: data.MediaType, ContentUri: data.Uri),
            _ => new("error", ErrorCode: "unsupported-content", ErrorMessage: $"Unsupported AI content type '{content.GetType().Name}'."),
        };

    public static AgentChatContent FromContentReference(
        DataContent content,
        SunderRpcContentReference reference)
        => new(
            "content-reference",
            Name: content.Name,
            MediaType: content.MediaType,
            ContentReference: reference);

    private static AIContent ToContent(
        AgentChatContent content,
        Func<SunderRpcContentReference, ReadOnlyMemory<byte>>? resolveContent)
        => content.Kind switch
        {
            "reasoning" => new TextReasoningContent(content.Text ?? string.Empty) { ProtectedData = content.ProtectedData },
            "text" => new TextContent(content.Text ?? string.Empty),
            "tool-call" => new FunctionCallContent(
                content.CallId ?? string.Empty,
                content.Name ?? string.Empty,
                DeserializeDictionary(content.Json)) { InformationalOnly = content.InformationalOnly },
            "tool-result" => new FunctionResultContent(content.CallId ?? string.Empty, DeserializeObject(content.Json)),
            "usage" => new UsageContent(new UsageDetails
            {
                InputTokenCount = content.Usage?.InputTokens,
                OutputTokenCount = content.Usage?.OutputTokens,
                TotalTokenCount = content.Usage?.TotalTokens,
                CachedInputTokenCount = content.Usage?.CachedInputTokens,
                ReasoningTokenCount = content.Usage?.ReasoningTokens,
            }),
            "content-reference" when content.ContentReference is { } reference && resolveContent is not null
                => new DataContent(resolveContent(reference), reference.MediaType) { Name = reference.FileName },
            "content-reference" when Uri.TryCreate(content.ContentUri, UriKind.Absolute, out var uri)
                => new DataContent(uri, content.MediaType ?? "application/octet-stream") { Name = content.Name },
            "error" => new ErrorContent(content.ErrorMessage ?? "Provider error.") { ErrorCode = content.ErrorCode, Details = content.Json },
            _ => new ErrorContent("Unsupported Agent RPC chat content."),
        };

    private static IDictionary<string, object?> DeserializeDictionary(string? json)
        => string.IsNullOrWhiteSpace(json)
            ? new Dictionary<string, object?>(StringComparer.Ordinal)
            : JsonSerializer.Deserialize<Dictionary<string, object?>>(json)
              ?? new Dictionary<string, object?>(StringComparer.Ordinal);

    private static object? DeserializeObject(string? json)
        => string.IsNullOrWhiteSpace(json) ? null : JsonSerializer.Deserialize<object>(json);

    private static object? DeserializeAdditionalProperty(string json)
    {
        using var document = JsonDocument.Parse(json);
        var value = document.RootElement;
        return value.ValueKind switch
        {
            JsonValueKind.String => value.GetString(),
            JsonValueKind.True => true,
            JsonValueKind.False => false,
            JsonValueKind.Null => null,
            JsonValueKind.Number when value.TryGetInt32(out var intValue) => intValue,
            JsonValueKind.Number when value.TryGetInt64(out var longValue) => longValue,
            JsonValueKind.Number when value.TryGetDecimal(out var decimalValue) => decimalValue,
            JsonValueKind.Number => value.GetDouble(),
            _ => value.Clone(),
        };
    }
}

public sealed record ChatCapabilitiesRequest(string? ModelId);
public sealed record AgentChatStreamRequest(string ProviderId, string ModelId, IReadOnlyList<AgentChatMessage> Messages, AgentChatOptions Options);
public sealed record AgentChatMessage(string Role, string? MessageId, string? AuthorName, IReadOnlyList<AgentChatContent> Contents);
public sealed record AgentChatTool(string Name, string? Description, string JsonSchema);
public sealed record AgentChatOptions(
    string? Instructions,
    string? ConversationId,
    string? ModelId,
    float? Temperature,
    int? MaxOutputTokens,
    float? TopP,
    int? TopK,
    float? FrequencyPenalty,
    float? PresencePenalty,
    long? Seed,
    bool? AllowMultipleToolCalls,
    string? ReasoningEffort,
    IReadOnlyList<AgentChatTool> Tools,
    IReadOnlyDictionary<string, string>? AdditionalProperties,
    string? ContinuationHandle);
public sealed record AgentChatContent(
    string Kind,
    string? Text = null,
    string? ProtectedData = null,
    string? CallId = null,
    string? Name = null,
    string? Json = null,
    bool InformationalOnly = false,
    string? MediaType = null,
    string? ContentUri = null,
    SunderRpcContentReference? ContentReference = null,
    AgentChatUsage? Usage = null,
    string? ErrorCode = null,
    string? ErrorMessage = null);
public sealed record AgentChatUsage(long? InputTokens, long? OutputTokens, long? TotalTokens, long? CachedInputTokens, long? ReasoningTokens);
public sealed record AgentChatStreamEvent(
    string Kind,
    string? Role = null,
    string? ResponseId = null,
    string? MessageId = null,
    string? ConversationId = null,
    string? ModelId = null,
    string? FinishReason = null,
    DateTimeOffset? CreatedAt = null,
    IReadOnlyList<AgentChatContent>? ContentItems = null,
    string? ContinuationHandle = null,
    string? ErrorCode = null,
    string? ErrorMessage = null,
    string? ErrorContent = null,
    string? ErrorFailureKind = null)
{
    public const string UpdateKind = "update";
    public const string ErrorKind = "error";
    [JsonIgnore]
    public IReadOnlyList<AgentChatContent> Contents => ContentItems ?? [];

    public static AgentChatStreamEvent Error(string code, string message, string content, string failureKind)
        => new(ErrorKind, ErrorCode: code, ErrorMessage: message, ErrorContent: content, ErrorFailureKind: failureKind);
}
