// <auto-generated />
using System.Diagnostics.CodeAnalysis;
using Sunder.Sdk.Rpc;

namespace Sunder.Package.Agent.Protocol;

public sealed class AgentRpcService<TClient>(
    string contractId,
    Func<ISunderRpcClient, SunderRpcEndpointReference, TClient> createClient)
    where TClient : class
{
    public string ContractId { get; } = contractId;

    internal TClient CreateClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint)
        => createClient(client, endpoint);
}

public sealed class AgentRpcProviderService<TClient>(
    string contractId,
    Func<ISunderRpcClient, SunderRpcProviderSnapshot, TClient> createClient)
    where TClient : class
{
    public string ContractId { get; } = contractId;

    internal TClient CreateClient(ISunderRpcClient client, SunderRpcProviderSnapshot provider)
        => createClient(client, provider);
}

public partial class AgentRpcCatalog : IDisposable
{
    private static readonly TimeSpan WatchRetryDelay = TimeSpan.FromMilliseconds(250);
    private readonly ISunderRpcClient _client;
    private readonly object _gate = new();
    private readonly Dictionary<string, Dictionary<string, IRetirableAgentRpcReference>> _references = new(StringComparer.Ordinal);
    private readonly CancellationTokenSource _lifetime = new();
    private Task? _watchTask;
    private AgentRpcCatalogAvailability _availability;
    private SunderRpcError? _availabilityError;
    private int _disposed;

    public AgentRpcCatalog(ISunderRpcClient client)
        : this(client, startWatching: true)
    {
    }

    private AgentRpcCatalog(ISunderRpcClient client, bool startWatching)
    {
        _client = client ?? throw new ArgumentNullException(nameof(client));
        if (startWatching) StartWatching();
    }

    public static AgentRpcCatalog CreateDormant(ISunderRpcClient client)
        => new(client, startWatching: false);

    public void StartWatching()
    {
        ObjectDisposedException.ThrowIf(Volatile.Read(ref _disposed) != 0, this);
        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(Volatile.Read(ref _disposed) != 0, this);
            _watchTask ??= WatchAsync();
        }
    }

    public event EventHandler<AgentRpcCatalogChangedEventArgs>? Changed;

    public event EventHandler? AvailabilityChanged;

    public AgentRpcCatalogAvailability Availability
    {
        get
        {
            lock (_gate) return _availability;
        }
    }

    public SunderRpcError? AvailabilityError
    {
        get
        {
            lock (_gate) return _availabilityError;
        }
    }

    public IReadOnlyList<AgentRpcReference<TClient>> GetServiceReferences<TClient>(AgentRpcService<TClient> service)
        where TClient : class
    {
        ObjectDisposedException.ThrowIf(Volatile.Read(ref _disposed) != 0, this);
        var snapshot = Discover(service.ContractId);
        if (snapshot is null) return [];
        var active = snapshot.Providers
            .Where(static provider => provider.State == SunderRpcProviderState.Active)
            .ToArray();
        lock (_gate)
        {
            if (!_references.TryGetValue(service.ContractId, out var known))
            {
                known = new Dictionary<string, IRetirableAgentRpcReference>(StringComparer.Ordinal);
                _references.Add(service.ContractId, known);
            }
            var endpoints = active.Select(static provider => provider.Endpoint.Value).ToHashSet(StringComparer.Ordinal);
            foreach (var removed in known.Where(pair => !endpoints.Contains(pair.Key)).ToArray())
            {
                removed.Value.Retire();
                known.Remove(removed.Key);
            }
            var result = new List<AgentRpcReference<TClient>>(active.Length);
            foreach (var provider in active)
            {
                if (!known.TryGetValue(provider.Endpoint.Value, out var value)
                    || value is not AgentRpcReference<TClient> reference
                    || !reference.CanReuse(provider))
                {
                    value?.Retire();
                    value = new AgentRpcReference<TClient>(_client, service, provider);
                    known[provider.Endpoint.Value] = value;
                }
                result.Add((AgentRpcReference<TClient>)value);
            }
            return result;
        }
    }

    public IReadOnlyList<AgentRpcProviderReference<TClient>> GetServiceReferences<TClient>(AgentRpcProviderService<TClient> service)
        where TClient : class
    {
        ObjectDisposedException.ThrowIf(Volatile.Read(ref _disposed) != 0, this);
        var snapshot = Discover(service.ContractId);
        if (snapshot is null) return [];
        var active = snapshot.Providers
            .Where(static provider => provider.State == SunderRpcProviderState.Active)
            .ToArray();
        lock (_gate)
        {
            if (!_references.TryGetValue(service.ContractId, out var known))
            {
                known = new Dictionary<string, IRetirableAgentRpcReference>(StringComparer.Ordinal);
                _references.Add(service.ContractId, known);
            }
            var endpoints = active.Select(static provider => provider.Endpoint.Value).ToHashSet(StringComparer.Ordinal);
            foreach (var removed in known.Where(pair => !endpoints.Contains(pair.Key)).ToArray())
            {
                removed.Value.Retire();
                known.Remove(removed.Key);
            }
            var result = new List<AgentRpcProviderReference<TClient>>(active.Length);
            foreach (var provider in active)
            {
                if (!known.TryGetValue(provider.Endpoint.Value, out var value)
                    || value is not AgentRpcProviderReference<TClient> reference
                    || !reference.CanReuse(provider))
                {
                    value?.Retire();
                    value = new AgentRpcProviderReference<TClient>(_client, service, provider);
                    known[provider.Endpoint.Value] = value;
                }
                result.Add((AgentRpcProviderReference<TClient>)value);
            }
            return result;
        }
    }

    public AgentRpcReference<TClient> GetServiceReference<TClient>(
        AgentRpcService<TClient> service,
        AgentRpcProviderHandle handle)
        where TClient : class
    {
        ObjectDisposedException.ThrowIf(Volatile.Read(ref _disposed) != 0, this);
        ArgumentNullException.ThrowIfNull(handle);
        if (!string.Equals(handle.ContractId, service.ContractId, StringComparison.Ordinal))
        {
            throw new SunderRpcException(new SunderRpcError(
                SunderRpcErrorKind.Validation,
                "agent.rpc.contract-mismatch",
                "The RPC provider handle does not match the requested contract."));
        }
        var provider = _client.GetProviderAsync(
                new SunderRpcEndpointReference(handle.EndpointReference),
                _lifetime.Token)
            .AsTask().GetAwaiter().GetResult();
        if (provider is null || !handle.Matches(provider))
        {
            throw new SunderRpcException(new SunderRpcError(
                SunderRpcErrorKind.StaleEndpoint,
                "agent.rpc.provider-stale",
                "The referenced RPC provider activation is stale."));
        }
        lock (_gate)
        {
            if (!_references.TryGetValue(service.ContractId, out var known))
            {
                known = new Dictionary<string, IRetirableAgentRpcReference>(StringComparer.Ordinal);
                _references.Add(service.ContractId, known);
            }
            if (!known.TryGetValue(provider.Endpoint.Value, out var value)
                || value is not AgentRpcReference<TClient> reference
                || !reference.CanReuse(provider))
            {
                value?.Retire();
                value = new AgentRpcReference<TClient>(_client, service, provider);
                known[provider.Endpoint.Value] = value;
            }
            return (AgentRpcReference<TClient>)value;
        }
    }

    internal bool TryGetServiceReference<TClient>(
        AgentRpcService<TClient> service,
        AgentRpcProviderHandle handle,
        [NotNullWhen(true)] out AgentRpcReference<TClient>? reference)
        where TClient : class
    {
        try
        {
            reference = GetServiceReference(service, handle);
            return true;
        }
        catch (SunderRpcException exception) when (
            exception.Error.Kind is SunderRpcErrorKind.StaleEndpoint or SunderRpcErrorKind.Unavailable)
        {
            reference = null;
            return false;
        }
    }

    public bool TryReportInvariantViolation<TClient>(AgentRpcReference<TClient> reference, Exception exception)
        where TClient : class
    {
        ArgumentNullException.ThrowIfNull(reference);
        ArgumentNullException.ThrowIfNull(exception);
        lock (_gate)
        {
            if (Volatile.Read(ref _disposed) != 0
                || !_references.TryGetValue(reference.Provider.ContractId, out var known)
                || !known.TryGetValue(reference.Endpoint.Value, out var current)
                || !ReferenceEquals(current, reference)
                || !reference.CanReuse(reference.Provider))
            {
                return false;
            }
        }

        try
        {
            return Task.Run(async () => await _client.TryReportInvariantViolationAsync(
                    reference.Endpoint,
                    exception,
                    _lifetime.Token).ConfigureAwait(false))
                .GetAwaiter()
                .GetResult();
        }
        catch
        {
            return false;
        }
    }

    public void Dispose()
    {
        if (Interlocked.Exchange(ref _disposed, 1) != 0) return;
        _lifetime.Cancel();
        Task? watchTask;
        lock (_gate)
        {
            foreach (var reference in _references.Values.SelectMany(static values => values.Values)) reference.Retire();
            _references.Clear();
            watchTask = _watchTask;
        }
        if (watchTask is null)
        {
            _lifetime.Dispose();
            return;
        }
        _ = watchTask.ContinueWith(
            static (_, state) => ((CancellationTokenSource)state!).Dispose(),
            _lifetime,
            CancellationToken.None,
            TaskContinuationOptions.ExecuteSynchronously,
            TaskScheduler.Default);
    }

    private async Task WatchAsync()
    {
        var revision = 0L;
        var sequence = 0L;
        while (!_lifetime.IsCancellationRequested)
        {
            try
            {
                await foreach (var item in _client.WatchAsync(revision, sequence, _lifetime.Token)
                                   .WithCancellation(_lifetime.Token).ConfigureAwait(false))
                {
                    revision = item.Revision;
                    sequence = item.Sequence;
                    if (item.Kind == SunderRpcCatalogEventKind.ResetRequired)
                    {
                        SetAvailability(AgentRpcCatalogAvailability.Available, null);
                        RetireAll();
                        RaiseChanged(AgentRpcCatalogChangedEventArgs.Reset);
                        continue;
                    }
                    if (item.Provider is not { } provider) continue;
                    SetAvailability(AgentRpcCatalogAvailability.Available, null);
                    if (item.Kind is SunderRpcCatalogEventKind.Removed
                        or SunderRpcCatalogEventKind.Deactivated
                        or SunderRpcCatalogEventKind.Faulted)
                    {
                        RetireEndpoint(provider.ContractId, provider.Endpoint.Value);
                    }
                    RaiseChanged(new AgentRpcCatalogChangedEventArgs(
                        new HashSet<string>([provider.ContractId], StringComparer.Ordinal),
                        false));
                }
            }
            catch (OperationCanceledException) when (_lifetime.IsCancellationRequested)
            {
                return;
            }
            catch (OperationCanceledException)
            {
                SetAvailability(AgentRpcCatalogAvailability.Unavailable, null);
            }
            catch (SunderRpcException exception)
            {
                SetAvailability(MapAvailability(exception), exception.Error);
            }
            catch
            {
                SetAvailability(AgentRpcCatalogAvailability.Faulted, null);
            }

            try
            {
                await Task.Delay(WatchRetryDelay, _lifetime.Token).ConfigureAwait(false);
            }
            catch (OperationCanceledException) when (_lifetime.IsCancellationRequested)
            {
                return;
            }
        }
    }

    private SunderRpcCatalogSnapshot? Discover(string contractId)
    {
        try
        {
            var snapshot = _client.DiscoverAsync(contractId, _lifetime.Token)
                .AsTask().GetAwaiter().GetResult();
            SetAvailability(AgentRpcCatalogAvailability.Available, null);
            return snapshot;
        }
        catch (SunderRpcException exception) when (exception.Error.Kind == SunderRpcErrorKind.Unavailable)
        {
            SetAvailability(AgentRpcCatalogAvailability.Unavailable, exception.Error);
            return null;
        }
        catch (SunderRpcException exception)
        {
            SetAvailability(MapAvailability(exception), exception.Error);
            throw;
        }
        catch
        {
            SetAvailability(AgentRpcCatalogAvailability.Faulted, null);
            throw;
        }
    }

    private async ValueTask<SunderRpcCatalogSnapshot?> DiscoverAsync(
        string contractId,
        CancellationToken cancellationToken)
    {
        using var invocation = CancellationTokenSource.CreateLinkedTokenSource(
            cancellationToken,
            _lifetime.Token);
        try
        {
            var snapshot = await _client.DiscoverAsync(contractId, invocation.Token).ConfigureAwait(false);
            SetAvailability(AgentRpcCatalogAvailability.Available, null);
            return snapshot;
        }
        catch (SunderRpcException exception) when (exception.Error.Kind == SunderRpcErrorKind.Unavailable)
        {
            SetAvailability(AgentRpcCatalogAvailability.Unavailable, exception.Error);
            return null;
        }
        catch (SunderRpcException exception) when (
            exception.Error.Kind == SunderRpcErrorKind.Cancelled
            && cancellationToken.IsCancellationRequested)
        {
            throw new OperationCanceledException(exception.Message, exception, cancellationToken);
        }
        catch (SunderRpcException exception) when (
            exception.Error.Kind == SunderRpcErrorKind.Cancelled
            && _lifetime.IsCancellationRequested)
        {
            throw;
        }
        catch (SunderRpcException exception)
        {
            SetAvailability(MapAvailability(exception), exception.Error);
            throw;
        }
        catch (OperationCanceledException) when (
            cancellationToken.IsCancellationRequested
            || _lifetime.IsCancellationRequested)
        {
            throw;
        }
        catch
        {
            SetAvailability(AgentRpcCatalogAvailability.Faulted, null);
            throw;
        }
    }

    private static AgentRpcCatalogAvailability MapAvailability(SunderRpcException exception)
        => exception.Error.Kind switch
        {
            SunderRpcErrorKind.PermissionDenied => AgentRpcCatalogAvailability.PermissionDenied,
            SunderRpcErrorKind.Unavailable => AgentRpcCatalogAvailability.Unavailable,
            _ => AgentRpcCatalogAvailability.Faulted,
        };

    private void SetAvailability(AgentRpcCatalogAvailability availability, SunderRpcError? error)
    {
        lock (_gate)
        {
            if (_availability == availability && Equals(_availabilityError, error)) return;
            _availability = availability;
            _availabilityError = error;
        }

        if (AvailabilityChanged is not { } handlers) return;
        foreach (EventHandler handler in handlers.GetInvocationList())
        {
            try
            {
                handler(this, EventArgs.Empty);
            }
            catch
            {
                // Availability observers cannot terminate catalog recovery.
            }
        }
    }

    private void RaiseChanged(AgentRpcCatalogChangedEventArgs args)
    {
        if (Changed is not { } handlers) return;
        foreach (EventHandler<AgentRpcCatalogChangedEventArgs> handler in handlers.GetInvocationList())
        {
            try
            {
                handler(this, args);
            }
            catch
            {
                // Projection observers cannot terminate the catalog watcher.
            }
        }
    }

    private void RetireEndpoint(string contractId, string endpoint)
    {
        lock (_gate)
        {
            if (_references.TryGetValue(contractId, out var references)
                && references.Remove(endpoint, out var reference))
            {
                reference.Retire();
            }
        }
    }

    private void RetireAll()
    {
        lock (_gate)
        {
            foreach (var reference in _references.Values.SelectMany(static values => values.Values)) reference.Retire();
            _references.Clear();
        }
    }
}

public sealed partial class AgentRpcProviderReference<TClient> : IRetirableAgentRpcReference
    where TClient : class
{
    private readonly ISunderRpcClient _client;
    private readonly CancellationTokenSource _retirement = new();
    private readonly TClient _binding;
    private int _retired;

    internal AgentRpcProviderReference(
        ISunderRpcClient client,
        AgentRpcProviderService<TClient> service,
        SunderRpcProviderSnapshot provider)
    {
        _client = client;
        Provider = provider;
        _binding = service.CreateClient(client, provider);
    }

    public SunderRpcProviderSnapshot Provider { get; }
    public string PackageId => Provider.PackageId;
    public string ProviderId => Provider.ProviderId;

    internal bool CanReuse(SunderRpcProviderSnapshot provider)
        => !_retirement.IsCancellationRequested
           && AgentRpcProviderHandle.From(Provider).Matches(provider);

    public bool TryAcquire([NotNullWhen(true)] out AgentRpcLease<TClient>? lease)
    {
        if (_retirement.IsCancellationRequested)
        {
            lease = null;
            return false;
        }
        SunderRpcProviderSnapshot? current;
        try
        {
            current = _client.GetProviderAsync(Provider.Endpoint, _retirement.Token).AsTask().GetAwaiter().GetResult();
        }
        catch (OperationCanceledException)
        {
            lease = null;
            return false;
        }
        catch (SunderRpcException exception) when (
            exception.Error.Kind is SunderRpcErrorKind.StaleEndpoint or SunderRpcErrorKind.Unavailable)
        {
            if (exception.Error.Kind == SunderRpcErrorKind.StaleEndpoint) Retire();
            lease = null;
            return false;
        }
        if (current is null
            || current.State != SunderRpcProviderState.Active
            || !AgentRpcProviderHandle.From(Provider).Matches(current))
        {
            Retire();
            lease = null;
            return false;
        }
        lease = new AgentRpcLease<TClient>(Provider.PackageId, _binding, _retirement.Token);
        return true;
    }

    void IRetirableAgentRpcReference.Retire() => Retire();

    private void Retire()
    {
        if (Interlocked.Exchange(ref _retired, 1) != 0) return;
        try
        {
            _retirement.Cancel();
        }
        catch
        {
            // Retirement observers cannot break catalog reconciliation.
        }
        try
        {
            (_binding as IDisposable)?.Dispose();
        }
        catch
        {
            // Retired client cleanup cannot break catalog reconciliation.
        }
    }
}

public sealed class AgentRpcCatalogChangedEventArgs(IReadOnlySet<string> contractIds, bool reset) : EventArgs
{
    public static AgentRpcCatalogChangedEventArgs Reset { get; } = new(new HashSet<string>(StringComparer.Ordinal), true);

    public IReadOnlySet<string> ContractIds { get; } = contractIds;

    public bool IsReset { get; } = reset;

    public bool IncludesContract(string contractId) => IsReset || ContractIds.Contains(contractId);
}

public sealed partial class AgentRpcReference<TClient> : IRetirableAgentRpcReference
    where TClient : class
{
    private readonly ISunderRpcClient _client;
    private readonly AgentRpcService<TClient> _service;
    private readonly CancellationTokenSource _retirement = new();
    private readonly TClient _clientBinding;
    private int _retired;

    internal AgentRpcReference(
        ISunderRpcClient client,
        AgentRpcService<TClient> service,
        SunderRpcProviderSnapshot provider)
    {
        _client = client;
        _service = service;
        Provider = provider;
        _clientBinding = service.CreateClient(client, provider.Endpoint);
    }

    public SunderRpcProviderSnapshot Provider { get; }

    public string PackageId => Provider.PackageId;

    public string ProviderId => Provider.ProviderId;

    public SunderRpcEndpointReference Endpoint => Provider.Endpoint;

    public AgentRpcProviderHandle ToHandle() => AgentRpcProviderHandle.From(Provider);

    internal bool CanReuse(SunderRpcProviderSnapshot provider)
        => !_retirement.IsCancellationRequested && ToHandle().Matches(provider);

    public bool TryAcquire([NotNullWhen(true)] out AgentRpcLease<TClient>? lease)
    {
        if (_retirement.IsCancellationRequested)
        {
            lease = null;
            return false;
        }
        SunderRpcProviderSnapshot? current;
        try
        {
            current = _client.GetProviderAsync(Provider.Endpoint, _retirement.Token).AsTask().GetAwaiter().GetResult();
        }
        catch (OperationCanceledException)
        {
            lease = null;
            return false;
        }
        catch (SunderRpcException exception) when (
            exception.Error.Kind is SunderRpcErrorKind.StaleEndpoint or SunderRpcErrorKind.Unavailable)
        {
            if (exception.Error.Kind == SunderRpcErrorKind.StaleEndpoint) Retire();
            lease = null;
            return false;
        }
        if (current is null
            || current.State != SunderRpcProviderState.Active
            || !ToHandle().Matches(current))
        {
            Retire();
            lease = null;
            return false;
        }
        lease = new AgentRpcLease<TClient>(Provider.PackageId, _clientBinding, _retirement.Token);
        return true;
    }

    void IRetirableAgentRpcReference.Retire() => Retire();

    private void Retire()
    {
        if (Interlocked.Exchange(ref _retired, 1) != 0) return;
        try
        {
            _retirement.Cancel();
        }
        catch
        {
            // Retirement observers cannot break catalog reconciliation.
        }
        try
        {
            (_clientBinding as IDisposable)?.Dispose();
        }
        catch
        {
            // Retired client cleanup cannot break catalog reconciliation.
        }
    }
}

public sealed class AgentRpcLease<TClient>(string packageId, TClient service, CancellationToken retirementToken) : IDisposable
    where TClient : class
{
    private int _disposed;

    public string PackageId
        => Volatile.Read(ref _disposed) == 0 ? packageId : throw new ObjectDisposedException(nameof(AgentRpcLease<TClient>));

    public TClient Service
        => Volatile.Read(ref _disposed) == 0 ? service : throw new ObjectDisposedException(nameof(AgentRpcLease<TClient>));

    public CancellationToken RetirementToken
        => Volatile.Read(ref _disposed) == 0 ? retirementToken : throw new ObjectDisposedException(nameof(AgentRpcLease<TClient>));

    public void Dispose() => Interlocked.Exchange(ref _disposed, 1);
}

internal interface IRetirableAgentRpcReference
{
    void Retire();
}

public enum AgentRpcCatalogAvailability
{
    Unknown,
    Available,
    Unavailable,
    PermissionDenied,
    Faulted,
}

public sealed record AgentRpcProviderHandle(
    string PackageId,
    string PackageVersion,
    string ProviderId,
    string ContractId,
    string ContractVersion,
    string ContractSha256,
    Guid ActivationId,
    long ActivationEpoch,
    long SessionGeneration,
    string EndpointReference)
{
    internal static AgentRpcProviderHandle From(SunderRpcProviderSnapshot provider)
        => new(
            provider.PackageId,
            provider.PackageVersion,
            provider.ProviderId,
            provider.ContractId,
            provider.ContractVersion,
            provider.ContractSha256,
            provider.ActivationId,
            provider.ActivationEpoch,
            provider.SessionGeneration,
            provider.Endpoint.Value);

    internal bool Matches(SunderRpcProviderSnapshot provider)
        => string.Equals(PackageId, provider.PackageId, StringComparison.Ordinal)
           && string.Equals(PackageVersion, provider.PackageVersion, StringComparison.Ordinal)
           && string.Equals(ProviderId, provider.ProviderId, StringComparison.Ordinal)
           && string.Equals(ContractId, provider.ContractId, StringComparison.Ordinal)
           && string.Equals(ContractVersion, provider.ContractVersion, StringComparison.Ordinal)
           && string.Equals(ContractSha256, provider.ContractSha256, StringComparison.Ordinal)
           && ActivationId == provider.ActivationId
           && ActivationEpoch == provider.ActivationEpoch
           && SessionGeneration == provider.SessionGeneration
           && string.Equals(EndpointReference, provider.Endpoint.Value, StringComparison.Ordinal);
}
