// <auto-generated />
using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Channels;
using Microsoft.Extensions.AI;
using Sunder.Package.Agent.Contracts.Contracts;
using Sunder.Package.Agent.Contracts.Models;
using Sunder.Sdk.Rpc;

namespace Sunder.Package.Agent.Protocol;

#pragma warning disable MEAI001

public static class AgentChatProviderRpc
{
    public const string ServiceId = "chat-provider";

    public static ISunderRpcServiceHandler CreateHandler(IAgentChatProvider provider)
    {
        var contentTransfers = new AgentChatContentTransferStore();
        return AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentProviderDescriptor>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(provider.Descriptor))
            .AddUnary<AgentRpcEmpty, IReadOnlyList<AgentModelDescriptor>>(ServiceId, "list-models", (_, _, token) => provider.GetAvailableModelsAsync(token))
            .AddUnary<AgentRpcEmpty, AgentProviderReadiness>(ServiceId, "get-readiness", (_, _, token) => provider.GetReadinessAsync(token))
            .AddUnary<ChatCapabilitiesRequest, AgentProviderRunCapabilities>(ServiceId, "get-capabilities", (_, request, token) => provider.GetRunCapabilitiesAsync(request.ModelId, token))
            .AddUnary<AgentRpcEmpty, AgentRpcOptional<string>>(ServiceId, "resolve-utility-model", async (_, _, token) =>
                new AgentRpcOptional<string>(
                    true,
                    provider is IAgentUtilityModelProvider utility
                        ? await utility.ResolveUtilityModelIdAsync(token).ConfigureAwait(false)
                        : null))
            .AddUnary<AgentChatContentChunk, AgentRpcEmpty>(ServiceId, "stage-content", (context, request, _) =>
            {
                contentTransfers.Stage(context.CallerPackageId, request);
                return ValueTask.FromResult(new AgentRpcEmpty());
            })
            .AddUnary<AgentChatContentDiscard, AgentRpcEmpty>(ServiceId, "discard-content", (context, request, _) =>
            {
                contentTransfers.Discard(context.CallerPackageId, request.ContentId);
                return ValueTask.FromResult(new AgentRpcEmpty());
            })
            .AddStream<AgentChatStreamRequest, AgentChatStreamEvent>(ServiceId, "stream-chat", (context, request, token) =>
                StreamAsync(provider, request, contentTransfers, context.CallerPackageId, token))
            .Build();
    }

    private static async IAsyncEnumerable<AgentChatStreamEvent> StreamAsync(
        IAgentChatProvider provider,
        AgentChatStreamRequest request,
        AgentChatContentTransferStore contentTransfers,
        string callerPackageId,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        var channel = Channel.CreateBounded<AgentChatStreamEvent>(new BoundedChannelOptions(64)
        {
            FullMode = BoundedChannelFullMode.Wait,
            SingleReader = true,
            SingleWriter = true,
        });
        var producer = ProduceAsync(
            provider,
            request,
            contentTransfers,
            callerPackageId,
            channel.Writer,
            cancellationToken);
        await foreach (var item in channel.Reader.ReadAllAsync(cancellationToken).ConfigureAwait(false))
        {
            yield return item;
        }
        await producer.ConfigureAwait(false);
    }

    private static async Task ProduceAsync(
        IAgentChatProvider provider,
        AgentChatStreamRequest request,
        AgentChatContentTransferStore contentTransfers,
        string callerPackageId,
        ChannelWriter<AgentChatStreamEvent> writer,
        CancellationToken cancellationToken)
    {
        IChatClient? chatClient = null;
        try
        {
            chatClient = await provider.CreateChatClientAsync(
                new AgentChatClientContext(request.ProviderId, request.ModelId),
                cancellationToken).ConfigureAwait(false);
            await foreach (var update in chatClient.GetStreamingResponseAsync(
                               request.Messages.Select(message => AgentChatWireMapper.ToChatMessage(
                                   message,
                                   reference => contentTransfers.Take(callerPackageId, reference))),
                               AgentChatWireMapper.ToChatOptions(request.Options),
                               cancellationToken).WithCancellation(cancellationToken).ConfigureAwait(false))
            {
                await writer.WriteAsync(AgentChatWireMapper.FromUpdate(update), cancellationToken).ConfigureAwait(false);
            }
        }
        catch (AgentChatProviderException exception)
        {
            await writer.WriteAsync(AgentChatStreamEvent.Error(
                exception.ErrorCode ?? "provider-error",
                exception.Message,
                exception.Content,
                exception.FailureKind.ToString()), cancellationToken).ConfigureAwait(false);
        }
        finally
        {
            chatClient?.Dispose();
            writer.TryComplete();
        }
    }
}

public sealed class AgentChatProviderRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentChatProvider, IAgentUtilityModelProvider
{
    private AgentProviderDescriptor? _descriptor;

    public AgentProviderDescriptor Descriptor
        => _descriptor ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentProviderDescriptor>(client, endpoint, AgentChatProviderRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();

    public ValueTask<IReadOnlyList<AgentModelDescriptor>> GetAvailableModelsAsync(CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, IReadOnlyList<AgentModelDescriptor>>(client, endpoint, AgentChatProviderRpc.ServiceId, "list-models", new AgentRpcEmpty(), cancellationToken);

    public ValueTask<AgentProviderReadiness> GetReadinessAsync(CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentProviderReadiness>(client, endpoint, AgentChatProviderRpc.ServiceId, "get-readiness", new AgentRpcEmpty(), cancellationToken);

    public ValueTask<AgentProviderRunCapabilities> GetRunCapabilitiesAsync(string? modelId, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<ChatCapabilitiesRequest, AgentProviderRunCapabilities>(client, endpoint, AgentChatProviderRpc.ServiceId, "get-capabilities", new(modelId), cancellationToken);

    public async ValueTask<string?> ResolveUtilityModelIdAsync(CancellationToken cancellationToken = default)
        => (await AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentRpcOptional<string>>(
            client,
            endpoint,
            AgentChatProviderRpc.ServiceId,
            "resolve-utility-model",
            new AgentRpcEmpty(),
            cancellationToken).ConfigureAwait(false)).Value;

    public ValueTask<IChatClient> CreateChatClientAsync(AgentChatClientContext context, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        return ValueTask.FromResult<IChatClient>(new AgentRpcChatClient(client, endpoint, context.ProviderId, context.ModelId));
    }
}

internal sealed class AgentRpcChatClient(
    ISunderRpcClient client,
    SunderRpcEndpointReference endpoint,
    string providerId,
    string modelId) : IChatClient
{
    public async Task<ChatResponse> GetResponseAsync(
        IEnumerable<ChatMessage> messages,
        ChatOptions? options = null,
        CancellationToken cancellationToken = default)
        => await GetStreamingResponseAsync(messages, options, cancellationToken)
            .ToChatResponseAsync(cancellationToken).ConfigureAwait(false);

    public async IAsyncEnumerable<ChatResponseUpdate> GetStreamingResponseAsync(
        IEnumerable<ChatMessage> messages,
        ChatOptions? options = null,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var stagedContent = new List<SunderRpcContentReference>();
        var mappedMessages = new List<AgentChatMessage>();
        foreach (var message in messages)
        {
            var mappedContents = new List<AgentChatContent>(message.Contents.Count);
            foreach (var content in message.Contents)
            {
                if (content is DataContent data && !data.Data.IsEmpty)
                {
                    var reference = await StageContentAsync(data, cancellationToken).ConfigureAwait(false);
                    stagedContent.Add(reference);
                    mappedContents.Add(AgentChatWireMapper.FromContentReference(data, reference));
                }
                else
                {
                    mappedContents.Add(AgentChatWireMapper.FromContent(content));
                }
            }
            mappedMessages.Add(AgentChatWireMapper.FromChatMessage(message, mappedContents));
        }
        var request = new AgentChatStreamRequest(
            providerId,
            modelId,
            mappedMessages,
            AgentChatWireMapper.FromChatOptions(options));
        try
        {
            await foreach (var item in AgentRpcServiceHandler.SubscribeAsync<AgentChatStreamRequest, AgentChatStreamEvent>(
                               client,
                               endpoint,
                               AgentChatProviderRpc.ServiceId,
                               "stream-chat",
                               request,
                               cancellationToken).WithCancellation(cancellationToken).ConfigureAwait(false))
            {
                if (item.Kind == AgentChatStreamEvent.ErrorKind)
                {
                    throw new AgentChatProviderException(
                        item.ErrorMessage ?? "Provider request failed.",
                        item.ErrorContent ?? item.ErrorMessage ?? "Provider request failed.",
                        item.ErrorCode)
                    {
                        FailureKind = Enum.TryParse<AgentChatProviderFailureKind>(item.ErrorFailureKind, out var kind)
                            ? kind
                            : AgentChatProviderFailureKind.Unknown,
                    };
                }
                yield return AgentChatWireMapper.ToUpdate(item);
            }
        }
        finally
        {
            foreach (var reference in stagedContent)
            {
                try
                {
                    _ = await AgentRpcServiceHandler.InvokeAsync<AgentChatContentDiscard, AgentRpcEmpty>(
                        client,
                        endpoint,
                        AgentChatProviderRpc.ServiceId,
                        "discard-content",
                        new(reference.Id),
                        CancellationToken.None).ConfigureAwait(false);
                }
                catch
                {
                    // Staged content is bounded and expires if the endpoint is no longer reachable.
                }
            }
        }
    }

    private async ValueTask<SunderRpcContentReference> StageContentAsync(
        DataContent content,
        CancellationToken cancellationToken)
    {
        if (content.Data.Length > AgentChatContentTransferStore.MaxContentBytes)
        {
            throw new SunderRpcException(new SunderRpcError(
                SunderRpcErrorKind.ResourceExhausted,
                "rpc.content.length-limit",
                "Chat binary content exceeds the transfer limit."));
        }
        var reference = new SunderRpcContentReference(
            "agent-chat-" + Guid.NewGuid().ToString("N"),
            content.Data.Length,
            Convert.ToHexString(SHA256.HashData(content.Data.Span)).ToLowerInvariant(),
            content.MediaType,
            string.IsNullOrWhiteSpace(content.Name) ? "content.bin" : content.Name,
            DateTimeOffset.UtcNow.AddMinutes(2),
            SunderRpcContentRepeatability.SingleUse);
        try
        {
            for (var offset = 0; offset < content.Data.Length; offset += AgentChatContentTransferStore.ChunkBytes)
            {
                var length = Math.Min(AgentChatContentTransferStore.ChunkBytes, content.Data.Length - offset);
                _ = await AgentRpcServiceHandler.InvokeAsync<AgentChatContentChunk, AgentRpcEmpty>(
                    client,
                    endpoint,
                    AgentChatProviderRpc.ServiceId,
                    "stage-content",
                    new(
                        reference,
                        offset,
                        Convert.ToBase64String(content.Data.Span.Slice(offset, length)),
                        offset + length == content.Data.Length),
                    cancellationToken).ConfigureAwait(false);
            }
            return reference;
        }
        catch
        {
            try
            {
                _ = await AgentRpcServiceHandler.InvokeAsync<AgentChatContentDiscard, AgentRpcEmpty>(
                    client,
                    endpoint,
                    AgentChatProviderRpc.ServiceId,
                    "discard-content",
                    new(reference.Id),
                    CancellationToken.None).ConfigureAwait(false);
            }
            catch
            {
            }
            throw;
        }
    }

    public object? GetService(Type serviceType, object? serviceKey = null) => null;

    public void Dispose()
    {
    }
}

internal static class AgentChatWireMapper
{
    public static AgentChatMessage FromChatMessage(ChatMessage message)
        => FromChatMessage(message, message.Contents.Select(FromContent).ToArray());

    public static AgentChatMessage FromChatMessage(
        ChatMessage message,
        IReadOnlyList<AgentChatContent> contents)
        => new(
            message.Role.Value,
            message.MessageId,
            message.AuthorName,
            contents);

    public static ChatMessage ToChatMessage(
        AgentChatMessage message,
        Func<SunderRpcContentReference, ReadOnlyMemory<byte>>? resolveContent = null)
        => new(new ChatRole(message.Role), message.Contents.Select(content => ToContent(content, resolveContent)).ToList())
        {
            MessageId = message.MessageId,
            AuthorName = message.AuthorName,
        };

    public static AgentChatOptions FromChatOptions(ChatOptions? options)
    {
        options ??= new ChatOptions();
        return new AgentChatOptions(
            options.Instructions,
            options.ConversationId,
            options.ModelId,
            options.Temperature,
            options.MaxOutputTokens,
            options.TopP,
            options.TopK,
            options.FrequencyPenalty,
            options.PresencePenalty,
            options.Seed,
            options.AllowMultipleToolCalls,
            options.Reasoning?.Effort.ToString(),
            options.Tools?.OfType<AIFunctionDeclaration>().Select(static tool => new AgentChatTool(
                tool.Name,
                tool.Description,
                tool.JsonSchema.GetRawText())).ToArray() ?? [],
            options.AdditionalProperties?.ToDictionary(
                static pair => pair.Key,
                static pair => JsonSerializer.Serialize(pair.Value),
                StringComparer.Ordinal),
            options.ContinuationToken is null
                ? null
                : Convert.ToBase64String(options.ContinuationToken.ToBytes().Span));
    }

    public static ChatOptions ToChatOptions(AgentChatOptions options)
    {
        var mapped = new ChatOptions
        {
            Instructions = options.Instructions,
            ConversationId = options.ConversationId,
            ModelId = options.ModelId,
            Temperature = options.Temperature,
            MaxOutputTokens = options.MaxOutputTokens,
            TopP = options.TopP,
            TopK = options.TopK,
            FrequencyPenalty = options.FrequencyPenalty,
            PresencePenalty = options.PresencePenalty,
            Seed = options.Seed,
            AllowMultipleToolCalls = options.AllowMultipleToolCalls,
            Tools = options.Tools.Select(static tool => (AITool)AIFunctionFactory.CreateDeclaration(
                tool.Name,
                tool.Description,
                JsonDocument.Parse(tool.JsonSchema).RootElement.Clone())).ToList(),
        };
        if (Enum.TryParse<ReasoningEffort>(options.ReasoningEffort, out var effort))
        {
            mapped.Reasoning = new ReasoningOptions { Effort = effort, Output = effort == ReasoningEffort.None ? ReasoningOutput.None : ReasoningOutput.Summary };
        }
        if (options.AdditionalProperties is { Count: > 0 })
        {
            mapped.AdditionalProperties = new AdditionalPropertiesDictionary();
            foreach (var pair in options.AdditionalProperties)
            {
                mapped.AdditionalProperties[pair.Key] = DeserializeAdditionalProperty(pair.Value);
            }
        }
        if (!string.IsNullOrWhiteSpace(options.ContinuationHandle))
        {
            mapped.ContinuationToken = ResponseContinuationToken.FromBytes(Convert.FromBase64String(options.ContinuationHandle));
        }
        return mapped;
    }

    public static AgentChatStreamEvent FromUpdate(ChatResponseUpdate update)
        => new(
            AgentChatStreamEvent.UpdateKind,
            update.Role?.Value,
            update.ResponseId,
            update.MessageId,
            update.ConversationId,
            update.ModelId,
            update.FinishReason?.Value,
            update.CreatedAt,
            update.Contents.Select(FromContent).ToArray(),
            update.ContinuationToken is null ? null : Convert.ToBase64String(update.ContinuationToken.ToBytes().Span));

    public static ChatResponseUpdate ToUpdate(AgentChatStreamEvent item)
        => new(
            item.Role is null ? null : new ChatRole(item.Role),
            item.Contents.Select(static content => ToContent(content, resolveContent: null)).ToList())
        {
            ResponseId = item.ResponseId,
            MessageId = item.MessageId,
            ConversationId = item.ConversationId,
            ModelId = item.ModelId,
            FinishReason = item.FinishReason is null ? null : new ChatFinishReason(item.FinishReason),
            CreatedAt = item.CreatedAt,
            ContinuationToken = item.ContinuationHandle is null
                ? null
                : ResponseContinuationToken.FromBytes(Convert.FromBase64String(item.ContinuationHandle)),
        };

    public static AgentChatContent FromContent(AIContent content)
        => content switch
        {
            TextReasoningContent reasoning => new("reasoning", Text: reasoning.Text, ProtectedData: reasoning.ProtectedData),
            TextContent text => new("text", Text: text.Text),
            FunctionCallContent call => new("tool-call", CallId: call.CallId, Name: call.Name, Json: JsonSerializer.Serialize(call.Arguments), InformationalOnly: call.InformationalOnly),
            FunctionResultContent result => new("tool-result", CallId: result.CallId, Json: JsonSerializer.Serialize(result.Result)),
            UsageContent usage => new("usage", Usage: new AgentChatUsage(
                usage.Details.InputTokenCount,
                usage.Details.OutputTokenCount,
                usage.Details.TotalTokenCount,
                usage.Details.CachedInputTokenCount,
                usage.Details.ReasoningTokenCount)),
            ErrorContent error => new("error", ErrorCode: error.ErrorCode, ErrorMessage: error.Message, Json: JsonSerializer.Serialize(error.Details)),
            DataContent data => new("content-reference", Name: data.Name, MediaType: data.MediaType, ContentUri: data.Uri),
            _ => new("error", ErrorCode: "unsupported-content", ErrorMessage: $"Unsupported AI content type '{content.GetType().Name}'."),
        };

    public static AgentChatContent FromContentReference(
        DataContent content,
        SunderRpcContentReference reference)
        => new(
            "content-reference",
            Name: content.Name,
            MediaType: content.MediaType,
            ContentReference: reference);

    private static AIContent ToContent(
        AgentChatContent content,
        Func<SunderRpcContentReference, ReadOnlyMemory<byte>>? resolveContent)
        => content.Kind switch
        {
            "reasoning" => new TextReasoningContent(content.Text ?? string.Empty) { ProtectedData = content.ProtectedData },
            "text" => new TextContent(content.Text ?? string.Empty),
            "tool-call" => new FunctionCallContent(
                content.CallId ?? string.Empty,
                content.Name ?? string.Empty,
                DeserializeDictionary(content.Json)) { InformationalOnly = content.InformationalOnly },
            "tool-result" => new FunctionResultContent(content.CallId ?? string.Empty, DeserializeObject(content.Json)),
            "usage" => new UsageContent(new UsageDetails
            {
                InputTokenCount = content.Usage?.InputTokens,
                OutputTokenCount = content.Usage?.OutputTokens,
                TotalTokenCount = content.Usage?.TotalTokens,
                CachedInputTokenCount = content.Usage?.CachedInputTokens,
                ReasoningTokenCount = content.Usage?.ReasoningTokens,
            }),
            "content-reference" when content.ContentReference is { } reference && resolveContent is not null
                => new DataContent(resolveContent(reference), reference.MediaType) { Name = reference.FileName },
            "content-reference" when Uri.TryCreate(content.ContentUri, UriKind.Absolute, out var uri)
                => new DataContent(uri, content.MediaType ?? "application/octet-stream") { Name = content.Name },
            "error" => new ErrorContent(content.ErrorMessage ?? "Provider error.") { ErrorCode = content.ErrorCode, Details = content.Json },
            _ => new ErrorContent("Unsupported Agent RPC chat content."),
        };

    private static IDictionary<string, object?> DeserializeDictionary(string? json)
        => string.IsNullOrWhiteSpace(json)
            ? new Dictionary<string, object?>(StringComparer.Ordinal)
            : JsonSerializer.Deserialize<Dictionary<string, object?>>(json)
              ?? new Dictionary<string, object?>(StringComparer.Ordinal);

    private static object? DeserializeObject(string? json)
        => string.IsNullOrWhiteSpace(json) ? null : JsonSerializer.Deserialize<object>(json);

    private static object? DeserializeAdditionalProperty(string json)
    {
        using var document = JsonDocument.Parse(json);
        var value = document.RootElement;
        return value.ValueKind switch
        {
            JsonValueKind.String => value.GetString(),
            JsonValueKind.True => true,
            JsonValueKind.False => false,
            JsonValueKind.Null => null,
            JsonValueKind.Number when value.TryGetInt32(out var intValue) => intValue,
            JsonValueKind.Number when value.TryGetInt64(out var longValue) => longValue,
            JsonValueKind.Number when value.TryGetDecimal(out var decimalValue) => decimalValue,
            JsonValueKind.Number => value.GetDouble(),
            _ => value.Clone(),
        };
    }
}

internal sealed class AgentChatContentTransferStore
{
    internal const int ChunkBytes = 384 * 1024;
    internal const int MaxContentBytes = 32 * 1024 * 1024;
    private const long MaxStoredBytes = 128L * 1024 * 1024;
    private const int MaxTransfersPerCaller = 16;
    private readonly object _gate = new();
    private readonly Dictionary<(string CallerPackageId, string ContentId), Entry> _entries = [];
    private long _storedBytes;

    internal void Stage(string callerPackageId, AgentChatContentChunk chunk)
    {
        ValidateReference(chunk.Reference);
        if (chunk.Offset < 0 || string.IsNullOrEmpty(chunk.Data) || chunk.Data.Length > 600_000)
        {
            throw Validation("rpc.content.chunk-invalid", "The chat content chunk is invalid.");
        }
        byte[] bytes;
        try
        {
            bytes = Convert.FromBase64String(chunk.Data);
        }
        catch (FormatException)
        {
            throw Validation("rpc.content.chunk-encoding", "The chat content chunk encoding is invalid.");
        }
        if (bytes.Length is <= 0 or > ChunkBytes)
        {
            throw Validation("rpc.content.chunk-limit", "The chat content chunk exceeds its size limit.");
        }

        lock (_gate)
        {
            SweepExpired(DateTimeOffset.UtcNow);
            var key = (callerPackageId, chunk.Reference.Id);
            if (!_entries.TryGetValue(key, out var entry))
            {
                if (chunk.Offset != 0
                    || _entries.Keys.Count(existing => existing.CallerPackageId == callerPackageId) >= MaxTransfersPerCaller
                    || _storedBytes + chunk.Reference.Length > MaxStoredBytes)
                {
                    throw ResourceExhausted("rpc.content.capacity", "Chat content transfer capacity is unavailable.");
                }
                entry = new Entry(chunk.Reference);
                _entries.Add(key, entry);
                _storedBytes += chunk.Reference.Length;
            }
            if (entry.Reference != chunk.Reference
                || entry.Complete
                || entry.Written != chunk.Offset
                || entry.Written + bytes.Length > entry.Data.Length)
            {
                Remove(key);
                throw Validation("rpc.content.sequence", "The chat content chunks are not a valid sequence.");
            }
            bytes.CopyTo(entry.Data, entry.Written);
            entry.Written += bytes.Length;
            entry.LastTouchedAtUtc = DateTimeOffset.UtcNow;
            if (chunk.IsFinal != (entry.Written == entry.Data.Length))
            {
                Remove(key);
                throw Validation("rpc.content.length", "The chat content length does not match its reference.");
            }
            if (chunk.IsFinal)
            {
                var hash = Convert.ToHexString(SHA256.HashData(entry.Data)).ToLowerInvariant();
                if (!string.Equals(hash, entry.Reference.Sha256, StringComparison.Ordinal))
                {
                    Remove(key);
                    throw Validation("rpc.content.hash", "The chat content hash does not match its reference.");
                }
                entry.Complete = true;
            }
        }
    }

    internal ReadOnlyMemory<byte> Take(string callerPackageId, SunderRpcContentReference reference)
    {
        ValidateReference(reference);
        lock (_gate)
        {
            SweepExpired(DateTimeOffset.UtcNow);
            var key = (callerPackageId, reference.Id);
            if (!_entries.TryGetValue(key, out var entry)
                || !entry.Complete
                || entry.Reference != reference)
            {
                throw Validation("rpc.content.unavailable", "The staged chat content is unavailable.");
            }
            _entries.Remove(key);
            _storedBytes -= entry.Data.LongLength;
            return entry.Data;
        }
    }

    internal void Discard(string callerPackageId, string contentId)
    {
        if (string.IsNullOrWhiteSpace(contentId) || contentId.Length > 128)
        {
            return;
        }
        lock (_gate)
        {
            Remove((callerPackageId, contentId));
        }
    }

    private static void ValidateReference(SunderRpcContentReference reference)
    {
        var now = DateTimeOffset.UtcNow;
        if (reference is null
            || string.IsNullOrWhiteSpace(reference.Id)
            || reference.Id.Length > 128
            || reference.Length is <= 0 or > MaxContentBytes
            || string.IsNullOrWhiteSpace(reference.Sha256)
            || reference.Sha256.Length != 64
            || reference.Sha256.Any(static value => !Uri.IsHexDigit(value))
            || string.IsNullOrWhiteSpace(reference.MediaType)
            || reference.MediaType.Length > 256
            || string.IsNullOrWhiteSpace(reference.FileName)
            || reference.FileName.Length > 512
            || reference.ExpiresAtUtc <= now
            || reference.ExpiresAtUtc > now.AddMinutes(5)
            || reference.Repeatability != SunderRpcContentRepeatability.SingleUse)
        {
            throw Validation("rpc.content.reference-invalid", "The chat content reference is invalid.");
        }
    }

    private void SweepExpired(DateTimeOffset now)
    {
        foreach (var key in _entries
                     .Where(item => item.Value.Reference.ExpiresAtUtc <= now
                                    || item.Value.LastTouchedAtUtc <= now.AddMinutes(-2))
                     .Select(static item => item.Key)
                     .ToArray())
        {
            Remove(key);
        }
    }

    private void Remove((string CallerPackageId, string ContentId) key)
    {
        if (_entries.Remove(key, out var removed))
        {
            _storedBytes -= removed.Data.LongLength;
        }
    }

    private static SunderRpcException Validation(string code, string message)
        => new(new SunderRpcError(SunderRpcErrorKind.Validation, code, message));

    private static SunderRpcException ResourceExhausted(string code, string message)
        => new(new SunderRpcError(SunderRpcErrorKind.ResourceExhausted, code, message));

    private sealed class Entry(SunderRpcContentReference reference)
    {
        public SunderRpcContentReference Reference { get; } = reference;
        public byte[] Data { get; } = new byte[checked((int)reference.Length)];
        public int Written { get; set; }
        public bool Complete { get; set; }
        public DateTimeOffset LastTouchedAtUtc { get; set; } = DateTimeOffset.UtcNow;
    }
}

public sealed record ChatCapabilitiesRequest(string? ModelId);
public sealed record AgentChatContentChunk(SunderRpcContentReference Reference, int Offset, string Data, bool IsFinal);
public sealed record AgentChatContentDiscard(string ContentId);
public sealed record AgentChatStreamRequest(string ProviderId, string ModelId, IReadOnlyList<AgentChatMessage> Messages, AgentChatOptions Options);
public sealed record AgentChatMessage(string Role, string? MessageId, string? AuthorName, IReadOnlyList<AgentChatContent> Contents);
public sealed record AgentChatTool(string Name, string? Description, string JsonSchema);
public sealed record AgentChatOptions(
    string? Instructions,
    string? ConversationId,
    string? ModelId,
    float? Temperature,
    int? MaxOutputTokens,
    float? TopP,
    int? TopK,
    float? FrequencyPenalty,
    float? PresencePenalty,
    long? Seed,
    bool? AllowMultipleToolCalls,
    string? ReasoningEffort,
    IReadOnlyList<AgentChatTool> Tools,
    IReadOnlyDictionary<string, string>? AdditionalProperties,
    string? ContinuationHandle);
public sealed record AgentChatContent(
    string Kind,
    string? Text = null,
    string? ProtectedData = null,
    string? CallId = null,
    string? Name = null,
    string? Json = null,
    bool InformationalOnly = false,
    string? MediaType = null,
    string? ContentUri = null,
    SunderRpcContentReference? ContentReference = null,
    AgentChatUsage? Usage = null,
    string? ErrorCode = null,
    string? ErrorMessage = null);
public sealed record AgentChatUsage(long? InputTokens, long? OutputTokens, long? TotalTokens, long? CachedInputTokens, long? ReasoningTokens);
public sealed record AgentChatStreamEvent(
    string Kind,
    string? Role = null,
    string? ResponseId = null,
    string? MessageId = null,
    string? ConversationId = null,
    string? ModelId = null,
    string? FinishReason = null,
    DateTimeOffset? CreatedAt = null,
    IReadOnlyList<AgentChatContent>? ContentItems = null,
    string? ContinuationHandle = null,
    string? ErrorCode = null,
    string? ErrorMessage = null,
    string? ErrorContent = null,
    string? ErrorFailureKind = null)
{
    public const string UpdateKind = "update";
    public const string ErrorKind = "error";
    [JsonIgnore]
    public IReadOnlyList<AgentChatContent> Contents => ContentItems ?? [];

    public static AgentChatStreamEvent Error(string code, string message, string content, string failureKind)
        => new(ErrorKind, ErrorCode: code, ErrorMessage: message, ErrorContent: content, ErrorFailureKind: failureKind);
}
