// <auto-generated />
using System.Runtime.CompilerServices;
using System.Threading.Channels;
using Sunder.Package.Agent.Contracts;
using Sunder.Package.Agent.Contracts.Contracts;
using Sunder.Package.Agent.Contracts.Models;
using Sunder.Sdk.Rpc;

namespace Sunder.Package.Agent.Protocol;

public static class AgentRpcContractIds
{
    public const string ChatProvider = "sunder.agent.chat.provider";
    public const string EmbeddingProvider = "sunder.agent.embedding.provider";
    public const string RuntimeCatalog = "sunder.agent.runtime.catalog";
    public const string WorkspaceExecutionResolver = "sunder.agent.workspace.execution.resolver";
    public const string ChildRunExecutor = "sunder.agent.child.run.executor";
    public const string SessionCleaner = "sunder.agent.session.cleaner";
    public const string SystemPromptContributor = "sunder.agent.system.prompt.contributor";
    public const string ToolSource = "sunder.agent.tool.source";
    public const string PermissionSurface = "sunder.agent.permission.surface";
    public const string PromptContextContributor = "sunder.agent.prompt.context.contributor";
    public const string DurableLifecycleObserver = "sunder.agent.durable.lifecycle.observer";
    public const string ProfileCapabilityConsumer = "sunder.agent.profile.capability.consumer";
    public const string SelectableCapabilityProvider = "sunder.agent.selectable.capability.provider";
    public const string BehaviorLoop = "sunder.agent.behavior.loop";
    public const string RunControl = "sunder.agent.run.control";
    public const string ExecutionTarget = "sunder.agent.execution.target";
    public const string WorkspacePathMigrator = "sunder.agent.workspace.path.migrator";
    public const string WorkspaceEditor = "sunder.agent.workspace.editor";
}

public static class AgentRpcServices
{
    public static AgentRpcService<IAgentChatProvider> ChatProviders { get; } = new(
        AgentRpcContractIds.ChatProvider,
        static (client, endpoint) => new AgentChatProviderRpcClient(client, endpoint));

    public static AgentRpcService<IAgentEmbeddingProvider> EmbeddingProviders { get; } = new(
        AgentRpcContractIds.EmbeddingProvider,
        static (client, endpoint) => new AgentEmbeddingProviderRpcClient(client, endpoint));

    public static AgentRpcService<IAgentExecutionTarget> ExecutionTargets { get; } = new(
        AgentRpcContractIds.ExecutionTarget,
        static (client, endpoint) => new AgentExecutionTargetRpcClient(client, endpoint));

    public static AgentRpcService<IAgentRuntimeCatalog> RuntimeCatalogs { get; } = new(
        AgentRpcContractIds.RuntimeCatalog,
        static (client, endpoint) => new AgentRuntimeCatalogRpcClient(client, endpoint));

    public static AgentRpcService<IAgentWorkspaceExecutionResolver> WorkspaceExecutionResolvers { get; } = new(
        AgentRpcContractIds.WorkspaceExecutionResolver,
        static (client, endpoint) => new AgentWorkspaceExecutionResolverRpcClient(client, endpoint));

    public static AgentRpcService<IAgentChildRunExecutor> ChildRunExecutors { get; } = new(
        AgentRpcContractIds.ChildRunExecutor,
        static (client, endpoint) => new AgentChildRunExecutorRpcClient(client, endpoint));

    public static AgentRpcService<IAgentSessionDataCleaner> SessionCleaners { get; } = new(
        AgentRpcContractIds.SessionCleaner,
        static (client, endpoint) => new AgentSessionCleanerRpcClient(client, endpoint));

    public static AgentRpcService<IAgentSystemPromptContributor> SystemPromptContributors { get; } = new(
        AgentRpcContractIds.SystemPromptContributor,
        static (client, endpoint) => new AgentSystemPromptContributorRpcClient(client, endpoint));

    public static AgentRpcService<IAgentToolSource> ToolSources { get; } = new(
        AgentRpcContractIds.ToolSource,
        static (client, endpoint) => new AgentToolSourceRpcClient(client, endpoint));

    public static AgentRpcService<IAgentPermissionSurface> PermissionSurfaces { get; } = new(
        AgentRpcContractIds.PermissionSurface,
        static (client, endpoint) => new AgentPermissionSurfaceRpcClient(client, endpoint));

    public static AgentRpcService<IAgentPromptContextContributor> PromptContextContributors { get; } = new(
        AgentRpcContractIds.PromptContextContributor,
        static (client, endpoint) => new AgentPromptContextContributorRpcClient(client, endpoint));

    public static AgentRpcService<IAgentDurableLifecycleObserver> DurableLifecycleObservers { get; } = new(
        AgentRpcContractIds.DurableLifecycleObserver,
        static (client, endpoint) => new AgentDurableLifecycleObserverRpcClient(client, endpoint));

    public static AgentRpcService<IAgentProfileCapabilityConsumer> ProfileCapabilityConsumers { get; } = new(
        AgentRpcContractIds.ProfileCapabilityConsumer,
        static (client, endpoint) => new AgentProfileCapabilityConsumerRpcClient(client, endpoint));

    public static AgentRpcService<IAgentProfileSelectableCapabilityProvider> SelectableCapabilityProviders { get; } = new(
        AgentRpcContractIds.SelectableCapabilityProvider,
        static (client, endpoint) => new AgentSelectableCapabilityProviderRpcClient(client, endpoint));

    public static AgentRpcService<IAgentWorkspacePathMigrationContributor> WorkspacePathMigrators { get; } = new(
        AgentRpcContractIds.WorkspacePathMigrator,
        static (client, endpoint) => new AgentWorkspacePathMigratorRpcClient(client, endpoint));

    public static AgentRpcService<IAgentWorkspaceEditorContributor> WorkspaceEditors { get; } = new(
        AgentRpcContractIds.WorkspaceEditor,
        static (client, endpoint) => new AgentWorkspaceEditorRpcClient(client, endpoint));

    public static AgentRpcService<AgentRunControlRpcClient> RunControls { get; } = new(
        AgentRpcContractIds.RunControl,
        static (client, endpoint) => new AgentRunControlRpcClient(client, endpoint));

    public static AgentRpcProviderService<IAgentBehaviorLoop> CreateBehaviorLoops(
        AgentRunControlRegistry runControls,
        AgentRpcCatalog rpcCatalog)
        => new(
            AgentRpcContractIds.BehaviorLoop,
            (client, provider) => new AgentBehaviorLoopRpcClient(client, provider, runControls, rpcCatalog));
}

public static class AgentEmbeddingProviderRpc
{
    private const string Service = "embedding-provider";

    public static ISunderRpcServiceHandler CreateHandler(IAgentEmbeddingProvider provider)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentEmbeddingProviderDescriptor>(Service, "describe", (_, _, _) => ValueTask.FromResult(provider.Descriptor))
            .AddUnary<AgentRpcEmpty, IReadOnlyList<AgentEmbeddingModelDescriptor>>(Service, "list-models", (_, _, token) => provider.GetAvailableModelsAsync(token))
            .AddUnary<AgentRpcEmpty, AgentEmbeddingProviderReadiness>(Service, "get-readiness", (_, _, token) => provider.GetReadinessAsync(token))
            .AddUnary<StringRequest, string>(Service, "space-identity", async (_, request, token) => provider is IAgentEmbeddingSpaceIdentityProvider identity
                ? await identity.GetEmbeddingSpaceIdentityAsync(request.Value, token).ConfigureAwait(false)
                : string.Empty)
            .AddUnary<EmbeddingRequest, AgentRpcOptional<AgentEmbeddingGenerationResult>>(Service, "generate", async (_, request, token) => new(true, await provider.GenerateEmbeddingAsync(request.ModelId, request.Text, token).ConfigureAwait(false)))
            .AddUnary<EmbeddingBatchRequest, IReadOnlyList<AgentEmbeddingGenerationResult?>>(Service, "generate-batch", (_, request, token) => provider.GenerateEmbeddingsAsync(request.ModelId, request.Texts, token))
            .Build();

    internal const string ServiceId = Service;
}

public sealed class AgentEmbeddingProviderRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentEmbeddingProvider, IAgentEmbeddingSpaceIdentityProvider
{
    private AgentEmbeddingProviderDescriptor? _descriptor;

    public AgentEmbeddingProviderDescriptor Descriptor
        => _descriptor ??= Invoke<AgentRpcEmpty, AgentEmbeddingProviderDescriptor>("describe", new AgentRpcEmpty());

    public ValueTask<IReadOnlyList<AgentEmbeddingModelDescriptor>> GetAvailableModelsAsync(CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, IReadOnlyList<AgentEmbeddingModelDescriptor>>(client, endpoint, AgentEmbeddingProviderRpc.ServiceId, "list-models", new AgentRpcEmpty(), cancellationToken);

    public ValueTask<AgentEmbeddingProviderReadiness> GetReadinessAsync(CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentEmbeddingProviderReadiness>(client, endpoint, AgentEmbeddingProviderRpc.ServiceId, "get-readiness", new AgentRpcEmpty(), cancellationToken);

    public ValueTask<string> GetEmbeddingSpaceIdentityAsync(string modelId, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<StringRequest, string>(client, endpoint, AgentEmbeddingProviderRpc.ServiceId, "space-identity", new(modelId), cancellationToken);

    public async ValueTask<AgentEmbeddingGenerationResult?> GenerateEmbeddingAsync(string modelId, string text, CancellationToken cancellationToken = default)
        => (await AgentRpcServiceHandler.InvokeAsync<EmbeddingRequest, AgentRpcOptional<AgentEmbeddingGenerationResult>>(client, endpoint, AgentEmbeddingProviderRpc.ServiceId, "generate", new(modelId, text), cancellationToken).ConfigureAwait(false)).Value;

    public ValueTask<IReadOnlyList<AgentEmbeddingGenerationResult?>> GenerateEmbeddingsAsync(string modelId, IReadOnlyList<string> texts, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<EmbeddingBatchRequest, IReadOnlyList<AgentEmbeddingGenerationResult?>>(client, endpoint, AgentEmbeddingProviderRpc.ServiceId, "generate-batch", new(modelId, texts), cancellationToken);

    private TResponse Invoke<TRequest, TResponse>(string method, TRequest request) where TRequest : notnull where TResponse : notnull
        => AgentRpcServiceHandler.InvokeAsync<TRequest, TResponse>(client, endpoint, AgentEmbeddingProviderRpc.ServiceId, method, request).AsTask().GetAwaiter().GetResult();
}

public static class AgentChildRunExecutorRpc
{
    public const string ServiceId = "child-run-executor";

    public static ISunderRpcServiceHandler CreateHandler(IAgentChildRunExecutor executor)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentChildRunRequest, AgentChildRunResult>(ServiceId, "run-child", (_, request, token) => executor.RunChildAsync(request, token))
            .Build();
}

public sealed class AgentChildRunExecutorRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentChildRunExecutor
{
    public ValueTask<AgentChildRunResult> RunChildAsync(AgentChildRunRequest request, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentChildRunRequest, AgentChildRunResult>(client, endpoint, AgentChildRunExecutorRpc.ServiceId, "run-child", request, cancellationToken);
}

public static class AgentSessionCleanerRpc
{
    public const string ServiceId = "session-cleaner";

    public static ISunderRpcServiceHandler CreateHandler(IAgentSessionDataCleaner cleaner)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentRpcIdentity>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(new AgentRpcIdentity(cleaner.CleanerId, cleaner.CleanerId)))
            .AddUnary<SessionIdRequest, AgentRpcEmpty>(ServiceId, "delete-session", (_, request, _) =>
            {
                cleaner.DeleteSessionData(request.SessionId);
                return ValueTask.FromResult(new AgentRpcEmpty());
            })
            .Build();
}

public sealed class AgentSessionCleanerRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentSessionDataCleaner
{
    private AgentRpcIdentity? _identity;

    public string CleanerId => (_identity ??= Describe()).Id;

    public void DeleteSessionData(Guid sessionId)
        => AgentRpcServiceHandler.InvokeAsync<SessionIdRequest, AgentRpcEmpty>(client, endpoint, AgentSessionCleanerRpc.ServiceId, "delete-session", new(sessionId)).AsTask().GetAwaiter().GetResult();

    private AgentRpcIdentity Describe()
        => AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentRpcIdentity>(client, endpoint, AgentSessionCleanerRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();
}

public static class AgentSystemPromptContributorRpc
{
    public const string ServiceId = "system-prompt-contributor";

    public static ISunderRpcServiceHandler CreateHandler(IAgentSystemPromptContributor contributor)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentRpcIdentity>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(new AgentRpcIdentity(contributor.ContributorId, contributor.DisplayName)))
            .AddUnary<AgentSystemPromptRequest, IReadOnlyList<AgentSystemPromptBlock>>(ServiceId, "contribute", (_, request, token) => contributor.ContributeAsync(request, token))
            .Build();
}

public sealed class AgentSystemPromptContributorRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentSystemPromptContributor
{
    private AgentRpcIdentity? _identity;
    private AgentRpcIdentity Identity => _identity ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentRpcIdentity>(client, endpoint, AgentSystemPromptContributorRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();
    public string ContributorId => Identity.Id;
    public string DisplayName => Identity.DisplayName;

    public ValueTask<IReadOnlyList<AgentSystemPromptBlock>> ContributeAsync(AgentSystemPromptRequest request, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentSystemPromptRequest, IReadOnlyList<AgentSystemPromptBlock>>(client, endpoint, AgentSystemPromptContributorRpc.ServiceId, "contribute", request, cancellationToken);
}

public static class AgentPermissionSurfaceRpc
{
    public const string ServiceId = "permission-surface";

    public static ISunderRpcServiceHandler CreateHandler(IAgentPermissionSurface surface)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, PermissionSurfaceSnapshot>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(new PermissionSurfaceSnapshot(surface.SurfaceId, surface.DisplayName, surface.ListActions())))
            .Build();
}

public sealed class AgentPermissionSurfaceRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentPermissionSurface
{
    private PermissionSurfaceSnapshot? _snapshot;
    private PermissionSurfaceSnapshot Snapshot => _snapshot ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, PermissionSurfaceSnapshot>(client, endpoint, AgentPermissionSurfaceRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();
    public string SurfaceId => Snapshot.SurfaceId;
    public string DisplayName => Snapshot.DisplayName;
    public IReadOnlyList<AgentPermissionActionDescriptor> ListActions() => Snapshot.Actions;
}

public static class AgentPromptContextContributorRpc
{
    public const string ServiceId = "prompt-context-contributor";

    public static ISunderRpcServiceHandler CreateHandler(
        IAgentPromptContextContributor contributor,
        AgentRpcCatalog? rpcCatalog = null)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, PromptContextContributorDescription>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(new PromptContextContributorDescription(
                contributor.ContributorId,
                contributor.DisplayName,
                (contributor as IAgentPromptContextAcknowledgmentSink)?.AcknowledgmentSinkId)))
            .AddUnary<PromptContextRequestWire, AgentRpcOptional<AgentPromptContextContribution>>(ServiceId, "contribute", async (_, request, token) => new(true, await contributor.ContributeContextAsync(
                request.ToRequest(rpcCatalog),
                token).ConfigureAwait(false)))
            .AddUnary<AgentPromptContextReceipt, AgentRpcEmpty>(ServiceId, "acknowledge", async (_, request, token) =>
            {
                if (contributor is IAgentPromptContextAcknowledgmentSink sink)
                {
                    await sink.AcknowledgePromptContextAsync(request, token).ConfigureAwait(false);
                }
                return new AgentRpcEmpty();
            })
            .Build();
}

public sealed class AgentPromptContextContributorRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentPromptContextContributor, IAgentPromptContextAcknowledgmentSink
{
    private PromptContextContributorDescription? _description;
    private PromptContextContributorDescription Description => _description ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, PromptContextContributorDescription>(client, endpoint, AgentPromptContextContributorRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();
    public string ContributorId => Description.ContributorId;
    public string DisplayName => Description.DisplayName;
    public string AcknowledgmentSinkId => Description.AcknowledgmentSinkId ?? Description.ContributorId;

    public async ValueTask<AgentPromptContextContribution?> ContributeContextAsync(AgentPromptContextRequest request, CancellationToken cancellationToken = default)
        => (await AgentRpcServiceHandler.InvokeAsync<PromptContextRequestWire, AgentRpcOptional<AgentPromptContextContribution>>(
            client,
            endpoint,
            AgentPromptContextContributorRpc.ServiceId,
            "contribute",
            PromptContextRequestWire.FromRequest(request),
            cancellationToken).ConfigureAwait(false)).Value;

    public async ValueTask AcknowledgePromptContextAsync(AgentPromptContextReceipt receipt, CancellationToken cancellationToken = default)
        => _ = await AgentRpcServiceHandler.InvokeAsync<AgentPromptContextReceipt, AgentRpcEmpty>(client, endpoint, AgentPromptContextContributorRpc.ServiceId, "acknowledge", receipt, cancellationToken).ConfigureAwait(false);
}

public sealed record PromptContextContributorDescription(string ContributorId, string DisplayName, string? AcknowledgmentSinkId);
public sealed record PromptContextRequestWire(
    AgentSessionContextRecord Session,
    AgentRunContextRecord Run,
    PromptContextTurnWire Turn,
    IReadOnlyList<AgentTurnRecord> Turns,
    IReadOnlyList<AgentTurnRecord> RecentLiveBufferTurns,
    AgentPromptContextPlan ContextPlan,
    AgentProfileRecord? Profile,
    AgentWorkspaceRecord? Workspace,
    AgentWorkspaceBindingRecord? ExecutionBinding,
    IReadOnlyList<AgentToolDescriptor> AvailableTools,
    AgentMemoryConsistencyBarrier? MemoryConsistencyBarrier,
    long TranscriptEpoch,
    AgentRpcProviderHandle? ExecutionTarget)
{
    public static PromptContextRequestWire FromRequest(AgentPromptContextRequest request)
        => new(
            request.Session,
            request.Run,
            new PromptContextTurnWire(request.Turn.UserMessage, request.Turn.WorkingSummary),
            request.Turns,
            request.RecentLiveBufferTurns,
            request.ContextPlan,
            request.Profile,
            request.Workspace,
            request.ExecutionBinding,
            request.AvailableTools,
            request.MemoryConsistencyBarrier,
            request.TranscriptEpoch,
            request.ExecutionTargetReference?.ToHandle());

    public AgentPromptContextRequest ToRequest(AgentRpcCatalog? rpcCatalog)
        => new(
            Session,
            Run,
            new AgentTurnContextRecord(Session, Run, Turn.UserMessage, Turn.WorkingSummary),
            Turns,
            RecentLiveBufferTurns,
            ContextPlan)
        {
            Profile = Profile,
            Workspace = Workspace,
            ExecutionBinding = ExecutionBinding,
            AvailableTools = AvailableTools,
            MemoryConsistencyBarrier = MemoryConsistencyBarrier,
            TranscriptEpoch = TranscriptEpoch,
            ExecutionTargetReference = ExecutionTarget is not null
                                       && rpcCatalog is not null
                                       && rpcCatalog.TryGetServiceReference(
                                           AgentRpcServices.ExecutionTargets,
                                           ExecutionTarget,
                                           out var reference)
                ? reference
                : null,
        };
}

public sealed record PromptContextTurnWire(string UserMessage, string? WorkingSummary);

public static class AgentDurableLifecycleObserverRpc
{
    public const string ServiceId = "durable-lifecycle-observer";

    public static ISunderRpcServiceHandler CreateHandler(IAgentDurableLifecycleObserver observer)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentRpcIdentity>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(new AgentRpcIdentity(observer.ObserverId, observer.DisplayName)))
            .AddUnary<AgentDurableLifecycleEventEnvelope, AgentRpcEmpty>(ServiceId, "handle", async (_, request, token) =>
            {
                await observer.HandleDurableLifecycleEventAsync(request, token).ConfigureAwait(false);
                return new AgentRpcEmpty();
            })
            .Build();
}

public sealed class AgentDurableLifecycleObserverRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentDurableLifecycleObserver
{
    private AgentRpcIdentity? _identity;
    private AgentRpcIdentity Identity => _identity ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentRpcIdentity>(client, endpoint, AgentDurableLifecycleObserverRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();
    public string ObserverId => Identity.Id;
    public string DisplayName => Identity.DisplayName;

    public async ValueTask HandleDurableLifecycleEventAsync(AgentDurableLifecycleEventEnvelope lifecycleEvent, CancellationToken cancellationToken = default)
        => _ = await AgentRpcServiceHandler.InvokeAsync<AgentDurableLifecycleEventEnvelope, AgentRpcEmpty>(client, endpoint, AgentDurableLifecycleObserverRpc.ServiceId, "handle", lifecycleEvent, cancellationToken).ConfigureAwait(false);
}

public static class AgentProfileCapabilityConsumerRpc
{
    public const string ServiceId = "profile-capability-consumer";

    public static ISunderRpcServiceHandler CreateHandler(IAgentProfileCapabilityConsumer consumer)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, ProfileCapabilityConsumerSnapshot>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(new ProfileCapabilityConsumerSnapshot(consumer.ConsumerId, consumer.DisplayName, consumer.ListConsumedCapabilities())))
            .Build();
}

public sealed class AgentProfileCapabilityConsumerRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentProfileCapabilityConsumer
{
    private ProfileCapabilityConsumerSnapshot? _snapshot;
    private ProfileCapabilityConsumerSnapshot Snapshot => _snapshot ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, ProfileCapabilityConsumerSnapshot>(client, endpoint, AgentProfileCapabilityConsumerRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();
    public string ConsumerId => Snapshot.ConsumerId;
    public string DisplayName => Snapshot.DisplayName;
    public IReadOnlyList<AgentProfileCapabilityConsumerDescriptor> ListConsumedCapabilities() => Snapshot.Capabilities;
}

public static class AgentSelectableCapabilityProviderRpc
{
    public const string ServiceId = "selectable-capability-provider";

    public static ISunderRpcServiceHandler CreateHandler(IAgentProfileSelectableCapabilityProvider provider)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentRpcIdentity>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(new AgentRpcIdentity(provider.ProviderId, provider.DisplayName)))
            .AddUnary<AgentProfileSelectableCapabilityRequest, IReadOnlyList<AgentProfileSelectableCapabilityDescriptor>>(ServiceId, "list", (_, request, token) => provider.ListCapabilitiesAsync(request, token))
            .AddStream<AgentRpcEmpty, AgentRpcChange>(ServiceId, "watch", (_, _, token) => WatchSelectableCapabilities(provider, token))
            .Build();

    private static async IAsyncEnumerable<AgentRpcChange> WatchSelectableCapabilities(
        IAgentProfileSelectableCapabilityProvider provider,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        if (provider is not IAgentProfileSelectableCapabilityChangeNotifier notifier)
        {
            await Task.Delay(Timeout.InfiniteTimeSpan, cancellationToken).ConfigureAwait(false);
            yield break;
        }
        var channel = Channel.CreateBounded<AgentRpcChange>(new BoundedChannelOptions(1)
        {
            FullMode = BoundedChannelFullMode.DropOldest,
            SingleReader = true,
            SingleWriter = false,
        });
        long revision = 0;
        void Changed() => channel.Writer.TryWrite(new AgentRpcChange(Interlocked.Increment(ref revision)));
        notifier.SelectableCapabilitiesChanged += Changed;
        try
        {
            await foreach (var change in channel.Reader.ReadAllAsync(cancellationToken).ConfigureAwait(false)) yield return change;
        }
        finally
        {
            notifier.SelectableCapabilitiesChanged -= Changed;
            channel.Writer.TryComplete();
        }
    }
}

public sealed class AgentSelectableCapabilityProviderRpcClient : IAgentProfileSelectableCapabilityProvider, IAgentProfileSelectableCapabilityChangeNotifier, IDisposable
{
    private readonly ISunderRpcClient _client;
    private readonly SunderRpcEndpointReference _endpoint;
    private readonly CancellationTokenSource _lifetime = new();
    private readonly Task _watch;
    private AgentRpcIdentity? _identity;

    public AgentSelectableCapabilityProviderRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint)
    {
        _client = client;
        _endpoint = endpoint;
        _watch = WatchAsync();
    }

    private AgentRpcIdentity Identity => _identity ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentRpcIdentity>(_client, _endpoint, AgentSelectableCapabilityProviderRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();
    public string ProviderId => Identity.Id;
    public string DisplayName => Identity.DisplayName;
    public event Action? SelectableCapabilitiesChanged;

    public ValueTask<IReadOnlyList<AgentProfileSelectableCapabilityDescriptor>> ListCapabilitiesAsync(AgentProfileSelectableCapabilityRequest request, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentProfileSelectableCapabilityRequest, IReadOnlyList<AgentProfileSelectableCapabilityDescriptor>>(_client, _endpoint, AgentSelectableCapabilityProviderRpc.ServiceId, "list", request, cancellationToken);

    public void Dispose()
    {
        _lifetime.Cancel();
        _ = _watch.ContinueWith(static (_, state) => ((CancellationTokenSource)state!).Dispose(), _lifetime, TaskScheduler.Default);
    }

    private async Task WatchAsync()
    {
        try
        {
            await foreach (var _ in AgentRpcServiceHandler.SubscribeAsync<AgentRpcEmpty, AgentRpcChange>(_client, _endpoint, AgentSelectableCapabilityProviderRpc.ServiceId, "watch", new AgentRpcEmpty(), _lifetime.Token).ConfigureAwait(false))
            {
                SelectableCapabilitiesChanged?.Invoke();
            }
        }
        catch (Exception exception) when (exception is OperationCanceledException or SunderRpcException)
        {
        }
    }
}

public static class AgentWorkspacePathMigratorRpc
{
    public const string ServiceId = "workspace-path-migrator";

    public static ISunderRpcServiceHandler CreateHandler(IAgentWorkspacePathMigrationContributor migrator)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentRpcIdentity>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(new AgentRpcIdentity(migrator.ContributorId, migrator.ContributorId)))
            .AddUnary<AgentWorkspacePathMigrationContext, bool>(ServiceId, "can-migrate", (_, request, _) => ValueTask.FromResult(migrator.CanMigrate(request)))
            .AddUnary<AgentWorkspacePathMigrationContext, IReadOnlyList<AgentWorkspacePathMigrationItem>>(ServiceId, "list-legacy-paths", async (_, request, token) => await migrator.GetLegacyWorkspacePathsAsync(request, token).ConfigureAwait(false))
            .AddUnary<AgentWorkspacePathMigrationContext, AgentRpcEmpty>(ServiceId, "complete", async (_, request, token) =>
            {
                await migrator.CompleteWorkspacePathMigrationAsync(request, token).ConfigureAwait(false);
                return new AgentRpcEmpty();
            })
            .Build();
}

public sealed class AgentWorkspacePathMigratorRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentWorkspacePathMigrationContributor
{
    private AgentRpcIdentity? _identity;
    public string ContributorId => (_identity ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentRpcIdentity>(client, endpoint, AgentWorkspacePathMigratorRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult()).Id;
    public bool CanMigrate(AgentWorkspacePathMigrationContext context)
        => AgentRpcServiceHandler.InvokeAsync<AgentWorkspacePathMigrationContext, bool>(client, endpoint, AgentWorkspacePathMigratorRpc.ServiceId, "can-migrate", context).AsTask().GetAwaiter().GetResult();
    public async Task<IReadOnlyList<AgentWorkspacePathMigrationItem>> GetLegacyWorkspacePathsAsync(AgentWorkspacePathMigrationContext context, CancellationToken cancellationToken = default)
        => await AgentRpcServiceHandler.InvokeAsync<AgentWorkspacePathMigrationContext, IReadOnlyList<AgentWorkspacePathMigrationItem>>(client, endpoint, AgentWorkspacePathMigratorRpc.ServiceId, "list-legacy-paths", context, cancellationToken).ConfigureAwait(false);
    public async Task CompleteWorkspacePathMigrationAsync(AgentWorkspacePathMigrationContext context, CancellationToken cancellationToken = default)
        => _ = await AgentRpcServiceHandler.InvokeAsync<AgentWorkspacePathMigrationContext, AgentRpcEmpty>(client, endpoint, AgentWorkspacePathMigratorRpc.ServiceId, "complete", context, cancellationToken).ConfigureAwait(false);
}

public static class AgentWorkspaceEditorRpc
{
    public const string ServiceId = "workspace-editor";

    public static ISunderRpcServiceHandler CreateHandler(IAgentWorkspaceEditorContributor editor)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentRpcIdentity>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(new AgentRpcIdentity(editor.ContributorId, editor.ContributorId)))
            .AddUnary<AgentWorkspaceEditorContext, bool>(ServiceId, "can-edit", (_, request, _) => ValueTask.FromResult(editor.CanEdit(request)))
            .AddUnary<AgentWorkspaceEditorContext, IReadOnlyList<AgentEditorSection>>(ServiceId, "get-sections", (_, request, token) => editor.GetSectionsAsync(request, token))
            .AddUnary<WorkspaceEditorSaveRequest, AgentEditorSaveResult>(ServiceId, "save-section", (_, request, token) => editor.SaveSectionAsync(request.Context, request.Request, token))
            .Build();
}

public sealed class AgentWorkspaceEditorRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint) : IAgentWorkspaceEditorContributor
{
    private AgentRpcIdentity? _identity;
    public string ContributorId => (_identity ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentRpcIdentity>(client, endpoint, AgentWorkspaceEditorRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult()).Id;
    public bool CanEdit(AgentWorkspaceEditorContext context)
        => AgentRpcServiceHandler.InvokeAsync<AgentWorkspaceEditorContext, bool>(client, endpoint, AgentWorkspaceEditorRpc.ServiceId, "can-edit", context).AsTask().GetAwaiter().GetResult();
    public ValueTask<IReadOnlyList<AgentEditorSection>> GetSectionsAsync(AgentWorkspaceEditorContext context, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentWorkspaceEditorContext, IReadOnlyList<AgentEditorSection>>(client, endpoint, AgentWorkspaceEditorRpc.ServiceId, "get-sections", context, cancellationToken);
    public ValueTask<AgentEditorSaveResult> SaveSectionAsync(AgentWorkspaceEditorContext context, AgentEditorSaveRequest request, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<WorkspaceEditorSaveRequest, AgentEditorSaveResult>(client, endpoint, AgentWorkspaceEditorRpc.ServiceId, "save-section", new(context, request), cancellationToken);
}

public sealed record AgentRpcIdentity(string Id, string DisplayName);
public sealed record AgentRpcOptional<T>(bool HasValue, T? Value);
public sealed record AgentRpcChange(long Revision);
public sealed record EmbeddingRequest(string ModelId, string Text);
public sealed record EmbeddingBatchRequest(string ModelId, IReadOnlyList<string> Texts);
public sealed record SessionIdRequest(Guid SessionId);
public sealed record PermissionSurfaceSnapshot(string SurfaceId, string DisplayName, IReadOnlyList<AgentPermissionActionDescriptor> Actions);
public sealed record ProfileCapabilityConsumerSnapshot(string ConsumerId, string DisplayName, IReadOnlyList<AgentProfileCapabilityConsumerDescriptor> Capabilities);
public sealed record WorkspaceEditorSaveRequest(AgentWorkspaceEditorContext Context, AgentEditorSaveRequest Request);
