// <auto-generated />
using Sunder.Package.Agent.Contracts.Contracts;
using Sunder.Package.Agent.Contracts.Models;
using Sunder.Sdk.Rpc;

namespace Sunder.Package.Agent.Protocol;

public static class AgentToolSourceRpc
{
    public const string ServiceId = "tool-source";

    public static ISunderRpcServiceHandler CreateHandler(IAgentToolSource source, AgentRpcCatalog? rpcCatalog = null)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, ToolSourceDescription>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(new ToolSourceDescription(source.SourceId, source.DisplayName, source.SourceKind)))
            .AddUnary<AgentToolSourceContextWire, IReadOnlyList<AgentToolDescriptor>>(ServiceId, "list-tools", (_, request, token) => source.ListToolsAsync(FromWire(request, rpcCatalog), token))
            .AddUnary<ToolReadinessRequest, AgentRpcOptional<AgentToolReadiness>>(ServiceId, "get-readiness", async (_, request, token) => new(true, await source.GetReadinessAsync(request.ToolId, FromWire(request.Context, rpcCatalog), token).ConfigureAwait(false)))
            .AddUnary<ToolInvocationRequest, AgentRpcOptional<AgentToolResult>>(ServiceId, "preflight", async (_, request, token) => new(true, source is IAgentToolExecutionPreflightSource preflight ? await preflight.PreflightExecutionAsync(FromWire(request.Context, rpcCatalog), request.Request, token).ConfigureAwait(false) : null))
            .AddUnary<ToolInvocationRequest, AgentToolResult>(ServiceId, "execute", (_, request, token) => source.ExecuteAsync(FromWire(request.Context, rpcCatalog), request.Request, token))
            .AddUnary<ToolInvocationRequest, AgentRpcOptional<AgentPermissionRequestWire>>(ServiceId, "permission", async (_, request, token) =>
            {
                var permissionRequest = source is IAgentPermissionAwareToolSource permission
                    ? await permission.BuildPermissionRequestAsync(FromWire(request.Context, rpcCatalog), request.Request, token).ConfigureAwait(false)
                    : null;
                return new(true, permissionRequest is null ? null : AgentPermissionRequestWire.FromRequest(permissionRequest));
            })
            .AddUnary<AgentToolPresentationRequest, AgentRpcOptional<AgentToolPresentation>>(ServiceId, "presentation", (_, request, _) => ValueTask.FromResult(new AgentRpcOptional<AgentToolPresentation>(true, source is IAgentToolPresentationResolver presentation ? presentation.ResolveToolPresentation(request) : null)))
            .Build();

    private static AgentToolSourceContext FromWire(AgentToolSourceContextWire wire, AgentRpcCatalog? rpcCatalog)
        => wire.Context with
        {
            ExecutionTargetReference = ResolveTarget(wire.ExecutionTarget, rpcCatalog),
            ExecutionTargetConfigurationGeneration = wire.ExecutionTargetConfigurationGeneration,
        };

    private static AgentToolExecutionContext FromWire(AgentToolExecutionContextWire wire, AgentRpcCatalog? rpcCatalog)
        => wire.Context with
        {
            ExecutionTargetReference = ResolveTarget(wire.ExecutionTarget, rpcCatalog),
            ApprovedResourceCapabilities = wire.ApprovedResourceCapabilities,
            ResourceOperation = wire.ResourceOperation?.ToContext(),
            ExecutionTargetConfigurationGeneration = wire.ExecutionTargetConfigurationGeneration,
        };

    private static AgentRpcReference<IAgentExecutionTarget>? ResolveTarget(
        AgentRpcProviderHandle? handle,
        AgentRpcCatalog? rpcCatalog)
        => handle is null || rpcCatalog is null
            ? null
            : rpcCatalog.GetServiceReference(AgentRpcServices.ExecutionTargets, handle);
}

public sealed class AgentToolSourceRpcClient :
    IAgentToolSource,
    IAgentPermissionAwareToolSource,
    IAgentToolExecutionPreflightSource,
    IAgentToolPresentationResolver
{
    private readonly ISunderRpcClient _client;
    private readonly SunderRpcEndpointReference _endpoint;
    private ToolSourceDescription? _description;

    public AgentToolSourceRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint)
    {
        _client = client;
        _endpoint = endpoint;
    }

    private ToolSourceDescription Description => _description ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, ToolSourceDescription>(
        _client, _endpoint, AgentToolSourceRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();

    public string SourceId => Description.SourceId;
    public string DisplayName => Description.DisplayName;
    public string SourceKind => Description.SourceKind;

    public ValueTask<IReadOnlyList<AgentToolDescriptor>> ListToolsAsync(AgentToolSourceContext context, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<AgentToolSourceContextWire, IReadOnlyList<AgentToolDescriptor>>(_client, _endpoint, AgentToolSourceRpc.ServiceId, "list-tools", ToWire(context), cancellationToken);

    public async ValueTask<AgentToolReadiness?> GetReadinessAsync(string toolId, AgentToolSourceContext context, CancellationToken cancellationToken = default)
        => (await AgentRpcServiceHandler.InvokeAsync<ToolReadinessRequest, AgentRpcOptional<AgentToolReadiness>>(_client, _endpoint, AgentToolSourceRpc.ServiceId, "get-readiness", new(toolId, ToWire(context)), cancellationToken).ConfigureAwait(false)).Value;

    public async ValueTask<AgentToolResult?> PreflightExecutionAsync(AgentToolExecutionContext context, AgentToolRequest request, CancellationToken cancellationToken = default)
        => (await AgentRpcServiceHandler.InvokeAsync<ToolInvocationRequest, AgentRpcOptional<AgentToolResult>>(_client, _endpoint, AgentToolSourceRpc.ServiceId, "preflight", new(ToWire(context), request), cancellationToken).ConfigureAwait(false)).Value;

    public ValueTask<AgentToolResult> ExecuteAsync(AgentToolExecutionContext context, AgentToolRequest request, CancellationToken cancellationToken = default)
        => AgentRpcServiceHandler.InvokeAsync<ToolInvocationRequest, AgentToolResult>(_client, _endpoint, AgentToolSourceRpc.ServiceId, "execute", new(ToWire(context), request), cancellationToken);

    public async ValueTask<AgentPermissionRequest?> BuildPermissionRequestAsync(AgentToolExecutionContext context, AgentToolRequest request, CancellationToken cancellationToken = default)
        => (await AgentRpcServiceHandler.InvokeAsync<ToolInvocationRequest, AgentRpcOptional<AgentPermissionRequestWire>>(_client, _endpoint, AgentToolSourceRpc.ServiceId, "permission", new(ToWire(context), request), cancellationToken).ConfigureAwait(false)).Value?.ToRequest();

    public AgentToolPresentation? ResolveToolPresentation(AgentToolPresentationRequest request)
        => AgentRpcServiceHandler.InvokeAsync<AgentToolPresentationRequest, AgentRpcOptional<AgentToolPresentation>>(_client, _endpoint, AgentToolSourceRpc.ServiceId, "presentation", request).AsTask().GetAwaiter().GetResult().Value;

    private static AgentToolSourceContextWire ToWire(AgentToolSourceContext context)
        => new(
            context,
            context.ExecutionTargetReference?.ToHandle(),
            context.ExecutionTargetConfigurationGeneration);

    private static AgentToolExecutionContextWire ToWire(AgentToolExecutionContext context)
        => new(
            context,
            context.ExecutionTargetReference?.ToHandle(),
            context.ApprovedResourceCapabilities,
            AgentResourceOperationContextWire.FromContext(context.ResourceOperation),
            context.ExecutionTargetConfigurationGeneration);
}

public sealed class AgentStaticToolSourceAdapter :
    IAgentToolSource,
    IAgentPermissionAwareToolSource,
    IAgentToolPresentationResolver
{
    private readonly IReadOnlyList<IAgentTool> _tools;

    public AgentStaticToolSourceAdapter(
        string sourceId,
        string displayName,
        string sourceKind,
        IEnumerable<IAgentTool> tools)
    {
        SourceId = sourceId;
        DisplayName = displayName;
        SourceKind = sourceKind;
        _tools = tools.ToArray();
    }

    public string SourceId { get; }
    public string DisplayName { get; }
    public string SourceKind { get; }

    public ValueTask<IReadOnlyList<AgentToolDescriptor>> ListToolsAsync(AgentToolSourceContext context, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        return ValueTask.FromResult<IReadOnlyList<AgentToolDescriptor>>(_tools.Select(static tool => tool.Descriptor).ToArray());
    }

    public ValueTask<AgentToolReadiness?> GetReadinessAsync(string toolId, AgentToolSourceContext context, CancellationToken cancellationToken = default)
    {
        var tool = Find(toolId);
        return tool is null
            ? ValueTask.FromResult<AgentToolReadiness?>(null)
            : AwaitReadiness(tool, cancellationToken);
    }

    public ValueTask<AgentToolResult> ExecuteAsync(AgentToolExecutionContext context, AgentToolRequest request, CancellationToken cancellationToken = default)
        => Find(request.ToolId) is { } tool
            ? tool.ExecuteAsync(context, request, cancellationToken)
            : ValueTask.FromResult(new AgentToolResult(request.ToolId, "Tool not found.", IsError: true, ErrorCode: "tool-not-found", BackendId: SourceId));

    public ValueTask<AgentPermissionRequest?> BuildPermissionRequestAsync(AgentToolExecutionContext context, AgentToolRequest request, CancellationToken cancellationToken = default)
        => Find(request.ToolId) is IAgentPermissionAwareTool permission
            ? permission.BuildPermissionRequestAsync(context, request, cancellationToken)
            : ValueTask.FromResult<AgentPermissionRequest?>(null);

    public AgentToolPresentation? ResolveToolPresentation(AgentToolPresentationRequest request)
        => Find(request.ToolId) is IAgentToolPresentationResolver presentation
            ? presentation.ResolveToolPresentation(request)
            : null;

    private IAgentTool? Find(string toolId)
        => _tools.FirstOrDefault(tool => string.Equals(tool.Descriptor.ToolId, toolId, StringComparison.OrdinalIgnoreCase));

    private static async ValueTask<AgentToolReadiness?> AwaitReadiness(IAgentTool tool, CancellationToken cancellationToken)
        => await tool.GetReadinessAsync(cancellationToken).ConfigureAwait(false);
}

public sealed record ToolSourceDescription(string SourceId, string DisplayName, string SourceKind);
public sealed record AgentToolSourceContextWire(AgentToolSourceContext Context, AgentRpcProviderHandle? ExecutionTarget, string? ExecutionTargetConfigurationGeneration);
public sealed record AgentToolExecutionContextWire(
    AgentToolExecutionContext Context,
    AgentRpcProviderHandle? ExecutionTarget,
    IReadOnlyList<string> ApprovedResourceCapabilities,
    AgentResourceOperationContextWire? ResourceOperation,
    string? ExecutionTargetConfigurationGeneration);
public sealed record AgentResourceOperationContextWire(
    Guid RunId,
    long RunRevision,
    string ToolCallId,
    string ActionId,
    int ResourceIndex,
    string WorkspaceGeneration,
    string BindingGeneration,
    string ToolOwnerPackageId,
    string ExecutionTargetOwnerPackageId,
    string AuthorityActivationId,
    int AuthorityUseCount,
    bool CanIssueOutsideAuthority)
{
    public static AgentResourceOperationContextWire? FromContext(AgentResourceOperationContext? context)
        => context is null
            ? null
            : new(
                context.RunId,
                context.RunRevision,
                context.ToolCallId,
                context.ActionId,
                context.ResourceIndex,
                context.WorkspaceGeneration,
                context.BindingGeneration,
                context.ToolOwnerPackageId,
                context.ExecutionTargetOwnerPackageId,
                context.AuthorityActivationId,
                context.AuthorityUseCount,
                context.CanIssueOutsideAuthority);

    public AgentResourceOperationContext ToContext()
        => new(
            RunId,
            RunRevision,
            ToolCallId,
            ActionId,
            ResourceIndex,
            WorkspaceGeneration,
            BindingGeneration,
            ToolOwnerPackageId,
            ExecutionTargetOwnerPackageId,
            AuthorityActivationId,
            AuthorityUseCount,
            CanIssueOutsideAuthority);
}
public sealed record ToolReadinessRequest(string ToolId, AgentToolSourceContextWire Context);
public sealed record ToolInvocationRequest(AgentToolExecutionContextWire Context, AgentToolRequest Request);
public sealed record AgentPermissionRequestWire(AgentPermissionRequest Request, IReadOnlyList<string> ResourceCapabilities)
{
    public static AgentPermissionRequestWire FromRequest(AgentPermissionRequest request)
        => new(request, request.ResourceCapabilities);

    public AgentPermissionRequest ToRequest()
        => Request with { ResourceCapabilities = ResourceCapabilities };
}
