// <auto-generated />
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using Sunder.Sdk.Rpc;

namespace Sunder.Package.Agent.Protocol;

public sealed record AgentRpcEmpty;

public sealed class AgentRpcServiceHandler : ISunderRpcServiceHandler
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };
    private readonly IReadOnlyDictionary<(string ServiceId, string MethodId), UnaryHandler> _unary;
    private readonly IReadOnlyDictionary<(string ServiceId, string MethodId), StreamHandler> _streams;

    private AgentRpcServiceHandler(
        IReadOnlyDictionary<(string ServiceId, string MethodId), UnaryHandler> unary,
        IReadOnlyDictionary<(string ServiceId, string MethodId), StreamHandler> streams)
    {
        _unary = unary;
        _streams = streams;
    }

    public static Builder Create() => new();

    public ValueTask<JsonElement> InvokeUnaryAsync(
        SunderRpcInvocationContext context,
        string serviceId,
        string methodId,
        JsonElement request,
        CancellationToken cancellationToken = default)
        => _unary.TryGetValue((serviceId, methodId), out var handler)
            ? handler(context, request, cancellationToken)
            : ValueTask.FromException<JsonElement>(NotFound(serviceId, methodId));

    public IAsyncEnumerable<JsonElement> InvokeServerStreamAsync(
        SunderRpcInvocationContext context,
        string serviceId,
        string methodId,
        JsonElement request,
        CancellationToken cancellationToken = default)
        => _streams.TryGetValue((serviceId, methodId), out var handler)
            ? handler(context, request, cancellationToken)
            : ThrowStream(NotFound(serviceId, methodId), cancellationToken);

    public sealed class Builder
    {
        private readonly Dictionary<(string ServiceId, string MethodId), UnaryHandler> _unary = [];
        private readonly Dictionary<(string ServiceId, string MethodId), StreamHandler> _streams = [];

        public Builder AddUnary<TRequest, TResponse>(
            string serviceId,
            string methodId,
            Func<SunderRpcInvocationContext, TRequest, CancellationToken, ValueTask<TResponse>> handler)
            where TRequest : notnull
            where TResponse : notnull
        {
            ArgumentNullException.ThrowIfNull(handler);
            if (!_unary.TryAdd((serviceId, methodId), async (context, request, cancellationToken) =>
                JsonSerializer.SerializeToElement(
                    await handler(
                        context,
                        Deserialize<TRequest>(request),
                        cancellationToken).ConfigureAwait(false),
                    JsonOptions)))
            {
                throw new InvalidOperationException($"Duplicate Agent RPC unary method '{serviceId}/{methodId}'.");
            }
            return this;
        }

        public Builder AddStream<TRequest, TEvent>(
            string serviceId,
            string methodId,
            Func<SunderRpcInvocationContext, TRequest, CancellationToken, IAsyncEnumerable<TEvent>> handler)
            where TRequest : notnull
            where TEvent : notnull
        {
            ArgumentNullException.ThrowIfNull(handler);
            if (!_streams.TryAdd((serviceId, methodId), (context, request, cancellationToken) =>
                SerializeStream(handler(context, Deserialize<TRequest>(request), cancellationToken), cancellationToken)))
            {
                throw new InvalidOperationException($"Duplicate Agent RPC stream method '{serviceId}/{methodId}'.");
            }
            return this;
        }

        public AgentRpcServiceHandler Build() => new(_unary, _streams);
    }

    public static ValueTask<TResponse> InvokeAsync<TRequest, TResponse>(
        ISunderRpcClient client,
        SunderRpcEndpointReference endpoint,
        string serviceId,
        string methodId,
        TRequest request,
        CancellationToken cancellationToken = default)
        where TRequest : notnull
        where TResponse : notnull
        => client.InvokeAsync<TRequest, TResponse>(
            endpoint,
            serviceId,
            methodId,
            request,
            cancellationToken: cancellationToken);

    public static IAsyncEnumerable<TEvent> SubscribeAsync<TRequest, TEvent>(
        ISunderRpcClient client,
        SunderRpcEndpointReference endpoint,
        string serviceId,
        string methodId,
        TRequest request,
        CancellationToken cancellationToken = default)
        where TRequest : notnull
        where TEvent : notnull
        => client.SubscribeAsync<TRequest, TEvent>(
            endpoint,
            serviceId,
            methodId,
            request,
            cancellationToken: cancellationToken);

    public static string Serialize<T>(T value)
        => JsonSerializer.Serialize(value, JsonOptions);

    private static T Deserialize<T>(JsonElement value)
        => value.Deserialize<T>(JsonOptions)
           ?? throw Protocol("agent.rpc.request.null", "The Agent RPC request deserialized to null.");

    private static async IAsyncEnumerable<JsonElement> SerializeStream<T>(
        IAsyncEnumerable<T> source,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        await foreach (var item in source.WithCancellation(cancellationToken).ConfigureAwait(false))
        {
            yield return JsonSerializer.SerializeToElement(item, JsonOptions);
        }
    }

    private static async IAsyncEnumerable<JsonElement> ThrowStream(
        Exception exception,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        await Task.CompletedTask;
        throw exception;
#pragma warning disable CS0162
        yield break;
#pragma warning restore CS0162
    }

    private static SunderRpcException NotFound(string serviceId, string methodId)
        => new(new SunderRpcError(
            SunderRpcErrorKind.NotFound,
            "agent.rpc.method-not-found",
            $"Agent RPC method '{serviceId}/{methodId}' is not implemented by this provider."));

    private static SunderRpcException Protocol(string code, string message)
        => new(new SunderRpcError(SunderRpcErrorKind.Protocol, code, message));

    private delegate ValueTask<JsonElement> UnaryHandler(
        SunderRpcInvocationContext context,
        JsonElement request,
        CancellationToken cancellationToken);

    private delegate IAsyncEnumerable<JsonElement> StreamHandler(
        SunderRpcInvocationContext context,
        JsonElement request,
        CancellationToken cancellationToken);
}
