// <auto-generated />
using System.Collections.Concurrent;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Threading.Channels;
using Microsoft.Extensions.AI;
using Sunder.Package.Agent.Contracts.Contracts;
using Sunder.Package.Agent.Contracts.Models;
using Sunder.Sdk.Logging;
using Sunder.Sdk.Rpc;

namespace Sunder.Package.Agent.Protocol;

#pragma warning disable MEAI001

public sealed class AgentRunControlRegistry
{
    private readonly ConcurrentDictionary<Guid, Registration> _registrations = new();

    public IDisposable Open(IAgentBehaviorLoopRuntime runtime, string callerPackageId, out Guid invocationId)
    {
        ArgumentNullException.ThrowIfNull(runtime);
        ArgumentException.ThrowIfNullOrWhiteSpace(callerPackageId);
        do invocationId = Guid.NewGuid();
        while (!_registrations.TryAdd(invocationId, new Registration(runtime, callerPackageId)));
        return new RegistrationLease(_registrations, invocationId);
    }

    internal IAgentBehaviorLoopRuntime Resolve(Guid invocationId, string callerPackageId)
    {
        if (!_registrations.TryGetValue(invocationId, out var registration)
            || !string.Equals(registration.CallerPackageId, callerPackageId, StringComparison.Ordinal))
        {
            throw new SunderRpcException(new SunderRpcError(
                SunderRpcErrorKind.PermissionDenied,
                "agent.run-control.invalid-invocation",
                "The behavior-loop run-control invocation is unavailable."));
        }
        return registration.Runtime;
    }

    private sealed record Registration(IAgentBehaviorLoopRuntime Runtime, string CallerPackageId);

    private sealed class RegistrationLease(
        ConcurrentDictionary<Guid, Registration> registrations,
        Guid invocationId) : IDisposable
    {
        private int _disposed;
        public void Dispose()
        {
            if (Interlocked.Exchange(ref _disposed, 1) == 0) registrations.TryRemove(invocationId, out _);
        }
    }
}

public static class AgentBehaviorLoopRpc
{
    public const string ServiceId = "behavior-loop";

    public static ISunderRpcServiceHandler CreateHandler(IAgentBehaviorLoop loop, AgentRpcCatalog rpcCatalog)
        => AgentRpcServiceHandler.Create()
            .AddUnary<AgentRpcEmpty, AgentBehaviorLoopDescriptor>(ServiceId, "describe", (_, _, _) => ValueTask.FromResult(loop.Descriptor))
            .AddUnary<BehaviorLoopRunRequest, AgentBehaviorLoopResult>(ServiceId, "run", (_, request, token) =>
                loop.RunAsync(request.Context, new AgentBehaviorLoopRuntimeRpcClient(rpcCatalog, request.InvocationId, request.RunControl), token))
            .Build();
}

public sealed class AgentBehaviorLoopRpcClient(
    ISunderRpcClient client,
    SunderRpcProviderSnapshot provider,
    AgentRunControlRegistry runControls,
    AgentRpcCatalog rpcCatalog) : IAgentBehaviorLoop
{
    private AgentBehaviorLoopDescriptor? _descriptor;

    public AgentBehaviorLoopDescriptor Descriptor
        => _descriptor ??= AgentRpcServiceHandler.InvokeAsync<AgentRpcEmpty, AgentBehaviorLoopDescriptor>(
            client, provider.Endpoint, AgentBehaviorLoopRpc.ServiceId, "describe", new AgentRpcEmpty()).AsTask().GetAwaiter().GetResult();

    public async ValueTask<AgentBehaviorLoopResult> RunAsync(
        AgentBehaviorLoopContext context,
        IAgentBehaviorLoopRuntime runtime,
        CancellationToken cancellationToken = default)
    {
        var runControl = rpcCatalog.GetServiceReferences(AgentRpcServices.RunControls)
            .FirstOrDefault(static reference =>
                string.Equals(reference.PackageId, "sunder.package.agent", StringComparison.Ordinal)
                && string.Equals(reference.ProviderId, AgentRunControlRpc.ProviderId, StringComparison.Ordinal))
            ?? throw new SunderRpcException(new SunderRpcError(
                SunderRpcErrorKind.Unavailable,
                "agent.run-control.unavailable",
                "The Agent run-control provider is unavailable."));
        if (!runControl.TryAcquire(out var runControlLease))
        {
            throw new SunderRpcException(new SunderRpcError(
                SunderRpcErrorKind.StaleEndpoint,
                "agent.run-control.stale",
                "The Agent run-control provider activation is stale."));
        }
        using (runControlLease)
        {
            using var registration = runControls.Open(runtime, provider.PackageId, out var invocationId);
            using var invocation = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, runControlLease.RetirementToken);
            return await AgentRpcServiceHandler.InvokeAsync<BehaviorLoopRunRequest, AgentBehaviorLoopResult>(
                    client,
                    provider.Endpoint,
                    AgentBehaviorLoopRpc.ServiceId,
                    "run",
                    new(invocationId, runControl.ToHandle(), context),
                    invocation.Token)
                .ConfigureAwait(false);
        }
    }
}

public static class AgentRunControlRpc
{
    public const string ProviderId = "agent.run.control";
    public const string ServiceId = "run-control";

    public static ISunderRpcServiceHandler CreateHandler(AgentRunControlRegistry registry)
    {
        var contentTransfers = new AgentChatContentTransferStore();
        return AgentRpcServiceHandler.Create()
            .AddUnary<RunControlInvocation, bool>(ServiceId, "is-current", (call, request, _) => ValueTask.FromResult(Resolve(registry, call, request).IsCurrentRun()))
            .AddUnary<RunControlInvocation, IReadOnlyList<AgentTurnRecord>>(ServiceId, "list-turns", (call, request, _) => ValueTask.FromResult(Resolve(registry, call, request).ListTurns()))
            .AddUnary<RunControlRecentTurnsRequest, IReadOnlyList<AgentTurnRecord>>(ServiceId, "list-recent-turns", (call, request, _) => ValueTask.FromResult(Resolve(registry, call, request.Invocation).ListRecentTurns(request.Limit)))
            .AddUnary<RunControlInvocation, AgentBehaviorInstructionContext>(ServiceId, "build-instruction-context", (call, request, token) => Resolve(registry, call, request).BuildInstructionContextAsync(token))
            .AddUnary<RunControlSessionProjectionRequest, AgentRpcEmpty>(ServiceId, "select-session-context", (call, request, _) =>
            {
                RequireCapability<IAgentSessionContextSelectionRuntime>(Resolve(registry, call, request.Invocation), "session context selection")
                    .SelectSessionContextProjection(request.Projection);
                return ValueTask.FromResult(new AgentRpcEmpty());
            })
            .AddUnary<RunControlActivityRequest, AgentRpcEmpty>(ServiceId, "report-activity", (call, request, _) =>
            {
                RequireCapability<IAgentRunActivitySink>(Resolve(registry, call, request.Invocation), "run activity")
                    .ReportRunActivity(request.Kind, request.Text);
                return ValueTask.FromResult(new AgentRpcEmpty());
            })
            .AddUnary<RunControlInvocation, AgentRunBudgetState>(ServiceId, "get-run-budget", (call, request, _) => ValueTask.FromResult(
                RequireCapability<IAgentRunBudgetRuntime>(Resolve(registry, call, request), "run budget").GetRunBudgetState()))
            .AddUnary<RunControlBudgetChargeRequest, AgentRunBudgetState>(ServiceId, "charge-run-budget", (call, request, _) => ValueTask.FromResult(
                RequireCapability<IAgentRunBudgetRuntime>(Resolve(registry, call, request.Invocation), "run budget").ChargeRunBudget(request.Charge)))
            .AddUnary<RunControlPromptContextRequest, AgentRpcEmpty>(ServiceId, "acknowledge-prompt-context", async (call, request, token) =>
            {
                if (Resolve(registry, call, request.Invocation) is not IAgentPromptContextAcknowledgmentRuntime runtime)
                {
                    throw new SunderRpcException(new SunderRpcError(
                        SunderRpcErrorKind.Domain,
                        "agent.run-control.prompt-context-acknowledgment-unavailable",
                        "The Agent run-control provider cannot acknowledge prompt context."));
                }
                await runtime.AcknowledgePromptContextAsync(request.Blocks, token).ConfigureAwait(false);
                return new AgentRpcEmpty();
            })
            .AddUnary<RunControlInvocation, AgentRpcEmpty>(ServiceId, "discard-prompt-context", (call, request, _) =>
            {
                if (Resolve(registry, call, request) is IAgentPromptContextAcknowledgmentRuntime runtime)
                {
                    runtime.DiscardPromptContextAcknowledgment();
                }
                return ValueTask.FromResult(new AgentRpcEmpty());
            })
            .AddUnary<RunControlInvocation, IReadOnlyList<AgentToolDescriptor>>(ServiceId, "list-ready-tools", async (call, request, token) =>
                (await Resolve(registry, call, request).ListReadyToolsAsync(token).ConfigureAwait(false)).Select(static tool => tool.Descriptor).ToArray())
            .AddUnary<RunControlCheckpointRequest, AgentRunCheckpointRecord>(ServiceId, "save-checkpoint", (call, request, _) => ValueTask.FromResult(Resolve(registry, call, request.Invocation).SaveCheckpoint(request.Status, request.Summary)))
            .AddUnary<RunControlLogRequest, AgentRpcEmpty>(ServiceId, "log-event", (call, request, _) =>
            {
                Resolve(registry, call, request.Invocation).LogEvent(request.Level, request.EventName, request.Message, request.ElapsedMilliseconds, request.Attributes?.ToDictionary(static pair => pair.Key, static pair => (object?)pair.Value, StringComparer.Ordinal));
                return ValueTask.FromResult(new AgentRpcEmpty());
            })
            .AddUnary<RunControlAssistantTurnRequest, AgentTurnRecord>(ServiceId, "upsert-assistant-turn", (call, request, _) => ValueTask.FromResult(Resolve(registry, call, request.Invocation).UpsertAssistantTurn(request.AssistantTurn, request.Content)))
            .AddUnary<RunControlCompleteTurnRequest, AgentTurnRecord>(ServiceId, "complete-assistant-turn", (call, request, _) => ValueTask.FromResult(Resolve(registry, call, request.Invocation).CompleteAssistantTurn(request.AssistantTurn)))
            .AddUnary<RunControlLifecycleRequest, AgentRpcEmpty>(ServiceId, "publish-lifecycle", async (call, request, token) =>
            {
                await Resolve(registry, call, request.Invocation).PublishLifecycleEventAsync(request.Kind, request.Status, request.TriggerTurn, request.Checkpoint, request.IsInterrupted, token).ConfigureAwait(false);
                return new AgentRpcEmpty();
            })
            .AddUnary<RunControlToolRequest, AgentToolCallOutcome>(ServiceId, "invoke-tool", (call, request, token) => Resolve(registry, call, request.Invocation).InvokeToolAsync(request.ToolCall, request.AssistantTurn, token))
            .AddUnary<RunControlToolsRequest, IReadOnlyList<AgentToolCallOutcome>>(ServiceId, "invoke-tools", (call, request, token) => Resolve(registry, call, request.Invocation).InvokeToolsAsync(request.ToolCalls, request.AssistantTurn, token))
            .AddUnary<RunControlDefaultLoopRequest, AgentBehaviorLoopResult>(ServiceId, "run-default", (call, request, token) =>
            {
                var runtime = Resolve(registry, call, request.Invocation);
                return runtime is IAgentInnerBehaviorLoopRuntime inner
                    ? inner.RunDefaultLoopAsync(request.Context, token)
                    : ValueTask.FromException<AgentBehaviorLoopResult>(new SunderRpcException(new SunderRpcError(
                        SunderRpcErrorKind.Domain,
                        "agent.run-control.default-loop-unavailable",
                        "The default behavior loop is unavailable.")));
            })
            .AddUnary<RunControlChatContentChunk, AgentRpcEmpty>(ServiceId, "stage-chat-content", (call, request, _) =>
            {
                Resolve(registry, call, request.Invocation);
                contentTransfers.Stage(call.CallerPackageId, request.Chunk);
                return ValueTask.FromResult(new AgentRpcEmpty());
            })
            .AddUnary<RunControlChatContentDiscard, AgentRpcEmpty>(ServiceId, "discard-chat-content", (call, request, _) =>
            {
                Resolve(registry, call, request.Invocation);
                contentTransfers.Discard(call.CallerPackageId, request.ContentId);
                return ValueTask.FromResult(new AgentRpcEmpty());
            })
            .AddStream<RunControlChatRequest, AgentChatStreamEvent>(ServiceId, "stream-chat", (call, request, token) => StreamChatAsync(
                Resolve(registry, call, request.Invocation),
                request,
                contentTransfers,
                call.CallerPackageId,
                token))
            .Build();
    }

    private static IAgentBehaviorLoopRuntime Resolve(
        AgentRunControlRegistry registry,
        SunderRpcInvocationContext call,
        RunControlInvocation invocation)
        => registry.Resolve(invocation.InvocationId, call.CallerPackageId);

    private static TCapability RequireCapability<TCapability>(IAgentBehaviorLoopRuntime runtime, string displayName)
        where TCapability : class
        => runtime as TCapability
           ?? throw new SunderRpcException(new SunderRpcError(
               SunderRpcErrorKind.Domain,
               "agent.run-control.capability-unavailable",
               $"The Agent run-control provider does not support {displayName}."));

    private static async IAsyncEnumerable<AgentChatStreamEvent> StreamChatAsync(
        IAgentBehaviorLoopRuntime runtime,
        RunControlChatRequest request,
        AgentChatContentTransferStore contentTransfers,
        string callerPackageId,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        var channel = Channel.CreateUnbounded<AgentChatStreamEvent>(new UnboundedChannelOptions
        {
            SingleReader = true,
            SingleWriter = true,
        });
        var producer = ProduceChatAsync(
            runtime,
            request,
            contentTransfers,
            callerPackageId,
            channel.Writer,
            cancellationToken);
        await foreach (var item in channel.Reader.ReadAllAsync(cancellationToken).ConfigureAwait(false))
        {
            yield return item;
        }
        await producer.ConfigureAwait(false);
    }

    private static async Task ProduceChatAsync(
        IAgentBehaviorLoopRuntime runtime,
        RunControlChatRequest request,
        AgentChatContentTransferStore contentTransfers,
        string callerPackageId,
        ChannelWriter<AgentChatStreamEvent> writer,
        CancellationToken cancellationToken)
    {
        IChatClient? chat = null;
        try
        {
            chat = await runtime.CreateChatClientAsync(
                new AgentChatClientContext(
                    request.Context.ProviderId,
                    request.Context.ModelId,
                    CorrelationAttributes: request.Context.CorrelationAttributes?.ToDictionary(static pair => pair.Key, static pair => (object?)pair.Value, StringComparer.Ordinal)),
                cancellationToken).ConfigureAwait(false);
            await foreach (var update in chat.GetStreamingResponseAsync(
                               request.Messages.Select(message => AgentChatWireMapper.ToChatMessage(
                                   message,
                                   reference => contentTransfers.Take(callerPackageId, reference))),
                               AgentChatWireMapper.ToChatOptions(request.Options),
                               cancellationToken).WithCancellation(cancellationToken).ConfigureAwait(false))
            {
                await writer.WriteAsync(AgentChatWireMapper.FromUpdate(update), cancellationToken).ConfigureAwait(false);
            }
        }
        catch (AgentChatProviderException exception)
        {
            await writer.WriteAsync(AgentChatStreamEvent.Error(
                exception.ErrorCode ?? "provider-error",
                exception.Message,
                exception.Content,
                exception.FailureKind.ToString()), cancellationToken).ConfigureAwait(false);
        }
        finally
        {
            chat?.Dispose();
            writer.TryComplete();
        }
    }
}

public sealed class AgentRunControlRpcClient(ISunderRpcClient client, SunderRpcEndpointReference endpoint)
{
    internal ValueTask<TResponse> InvokeAsync<TRequest, TResponse>(string methodId, TRequest request, CancellationToken cancellationToken = default)
        where TRequest : notnull
        where TResponse : notnull
        => AgentRpcServiceHandler.InvokeAsync<TRequest, TResponse>(client, endpoint, AgentRunControlRpc.ServiceId, methodId, request, cancellationToken);

    internal IAsyncEnumerable<AgentChatStreamEvent> StreamChatAsync(RunControlChatRequest request, CancellationToken cancellationToken)
        => AgentRpcServiceHandler.SubscribeAsync<RunControlChatRequest, AgentChatStreamEvent>(client, endpoint, AgentRunControlRpc.ServiceId, "stream-chat", request, cancellationToken);
}

internal sealed class AgentBehaviorLoopRuntimeRpcClient :
    IAgentBehaviorLoopRuntime,
    IAgentInnerBehaviorLoopRuntime,
    IAgentSessionContextSelectionRuntime,
    IAgentRunActivitySink,
    IAgentRunBudgetRuntime,
    IAgentPromptContextAcknowledgmentRuntime
{
    private readonly AgentRpcReference<AgentRunControlRpcClient> _runControl;
    private readonly Guid _invocationId;

    internal AgentBehaviorLoopRuntimeRpcClient(
        AgentRpcCatalog catalog,
        Guid invocationId,
        AgentRpcProviderHandle runControl)
    {
        _runControl = catalog.GetServiceReference(AgentRpcServices.RunControls, runControl);
        _invocationId = invocationId;
    }

    private RunControlInvocation Invocation => new(_invocationId);

    public bool IsCurrentRun() => Invoke<RunControlInvocation, bool>("is-current", Invocation);
    public IReadOnlyList<AgentTurnRecord> ListTurns() => Invoke<RunControlInvocation, IReadOnlyList<AgentTurnRecord>>("list-turns", Invocation);
    public IReadOnlyList<AgentTurnRecord> ListRecentTurns(int limit) => Invoke<RunControlRecentTurnsRequest, IReadOnlyList<AgentTurnRecord>>("list-recent-turns", new(Invocation, limit));
    public ValueTask<AgentBehaviorInstructionContext> BuildInstructionContextAsync(CancellationToken cancellationToken = default) => InvokeAsync<RunControlInvocation, AgentBehaviorInstructionContext>("build-instruction-context", Invocation, cancellationToken);

    public void SelectSessionContextProjection(AgentSessionPromptProjection projection)
        => _ = Invoke<RunControlSessionProjectionRequest, AgentRpcEmpty>("select-session-context", new(Invocation, projection));

    public void ReportRunActivity(AgentRunActivityKind kind, string text)
        => _ = Invoke<RunControlActivityRequest, AgentRpcEmpty>("report-activity", new(Invocation, kind, text));

    public AgentRunBudgetState GetRunBudgetState()
        => Invoke<RunControlInvocation, AgentRunBudgetState>("get-run-budget", Invocation);

    public AgentRunBudgetState ChargeRunBudget(AgentRunBudgetCharge charge)
        => Invoke<RunControlBudgetChargeRequest, AgentRunBudgetState>("charge-run-budget", new(Invocation, charge));

    public async ValueTask AcknowledgePromptContextAsync(
        IReadOnlyList<AgentPromptContextReceiptBlock> blocks,
        CancellationToken cancellationToken)
        => _ = await InvokeAsync<RunControlPromptContextRequest, AgentRpcEmpty>(
            "acknowledge-prompt-context",
            new(Invocation, blocks),
            cancellationToken).ConfigureAwait(false);

    public void DiscardPromptContextAcknowledgment()
        => _ = Invoke<RunControlInvocation, AgentRpcEmpty>("discard-prompt-context", Invocation);

    public async ValueTask<IReadOnlyList<AgentRuntimeTool>> ListReadyToolsAsync(CancellationToken cancellationToken = default)
    {
        var descriptors = await InvokeAsync<RunControlInvocation, IReadOnlyList<AgentToolDescriptor>>("list-ready-tools", Invocation, cancellationToken).ConfigureAwait(false);
        return descriptors.Select(static descriptor => new AgentRuntimeTool(
            descriptor,
            AIFunctionFactory.CreateDeclaration(
                descriptor.ToolId,
                descriptor.Description,
                string.IsNullOrWhiteSpace(descriptor.ArgumentsJsonSchema)
                    ? JsonSerializer.SerializeToElement(new { type = "object", properties = new { }, additionalProperties = false })
                    : JsonDocument.Parse(descriptor.ArgumentsJsonSchema).RootElement.Clone()))).ToArray();
    }

    public ValueTask<IChatClient> CreateChatClientAsync(AgentChatClientContext context, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var wire = new RunControlChatContext(
            context.ProviderId,
            context.ModelId,
            context.CorrelationAttributes?.ToDictionary(static pair => pair.Key, static pair => JsonSerializer.Serialize(pair.Value), StringComparer.Ordinal));
        return ValueTask.FromResult<IChatClient>(new AgentRunControlChatClient(this, wire));
    }

    public AgentRunCheckpointRecord SaveCheckpoint(AgentRunStatus status, string? summary) => Invoke<RunControlCheckpointRequest, AgentRunCheckpointRecord>("save-checkpoint", new(Invocation, status, summary));

    public void LogEvent(PackageLogLevel level, string eventName, string message, long? elapsedMilliseconds = null, IReadOnlyDictionary<string, object?>? attributes = null, Exception? exception = null)
        => _ = Invoke<RunControlLogRequest, AgentRpcEmpty>("log-event", new(
            Invocation,
            level,
            eventName,
            message,
            elapsedMilliseconds,
            attributes?.ToDictionary(static pair => pair.Key, static pair => JsonSerializer.Serialize(pair.Value), StringComparer.Ordinal),
            exception?.GetType().FullName,
            exception?.Message));

    public AgentTurnRecord UpsertAssistantTurn(AgentTurnRecord? assistantTurn, string content) => Invoke<RunControlAssistantTurnRequest, AgentTurnRecord>("upsert-assistant-turn", new(Invocation, assistantTurn, content));
    public AgentTurnRecord CompleteAssistantTurn(AgentTurnRecord assistantTurn) => Invoke<RunControlCompleteTurnRequest, AgentTurnRecord>("complete-assistant-turn", new(Invocation, assistantTurn));

    public async ValueTask PublishLifecycleEventAsync(AgentLifecycleEventKind kind, AgentRunStatus status, AgentTurnRecord? triggerTurn = null, AgentRunCheckpointRecord? checkpoint = null, bool isInterrupted = false, CancellationToken cancellationToken = default)
        => _ = await InvokeAsync<RunControlLifecycleRequest, AgentRpcEmpty>("publish-lifecycle", new(Invocation, kind, status, triggerTurn, checkpoint, isInterrupted), cancellationToken).ConfigureAwait(false);

    public ValueTask<AgentToolCallOutcome> InvokeToolAsync(AgentToolCallRequest toolCall, AgentTurnRecord? assistantTurn, CancellationToken cancellationToken = default)
        => InvokeAsync<RunControlToolRequest, AgentToolCallOutcome>("invoke-tool", new(Invocation, toolCall, assistantTurn), cancellationToken);

    public ValueTask<IReadOnlyList<AgentToolCallOutcome>> InvokeToolsAsync(IReadOnlyList<AgentToolCallRequest> toolCalls, AgentTurnRecord? assistantTurn, CancellationToken cancellationToken = default)
        => InvokeAsync<RunControlToolsRequest, IReadOnlyList<AgentToolCallOutcome>>("invoke-tools", new(Invocation, toolCalls, assistantTurn), cancellationToken);

    public ValueTask<AgentBehaviorLoopResult> RunDefaultLoopAsync(AgentBehaviorLoopContext context, CancellationToken cancellationToken = default)
        => InvokeAsync<RunControlDefaultLoopRequest, AgentBehaviorLoopResult>("run-default", new(Invocation, context), cancellationToken);

    internal IAsyncEnumerable<AgentChatStreamEvent> StreamChatAsync(
        RunControlChatContext context,
        IReadOnlyList<AgentChatMessage> messages,
        AgentChatOptions options,
        CancellationToken cancellationToken)
        => WithControlStream(control => control.StreamChatAsync(new(Invocation, context, messages, options), cancellationToken), cancellationToken);

    internal async ValueTask<SunderRpcContentReference> StageChatContentAsync(
        DataContent content,
        CancellationToken cancellationToken)
    {
        if (content.Data.Length > AgentChatContentTransferStore.MaxContentBytes)
        {
            throw new SunderRpcException(new SunderRpcError(
                SunderRpcErrorKind.ResourceExhausted,
                "rpc.content.length-limit",
                "Chat binary content exceeds the transfer limit."));
        }
        var reference = new SunderRpcContentReference(
            "agent-chat-" + Guid.NewGuid().ToString("N"),
            content.Data.Length,
            Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(content.Data.Span)).ToLowerInvariant(),
            content.MediaType,
            string.IsNullOrWhiteSpace(content.Name) ? "content.bin" : content.Name,
            DateTimeOffset.UtcNow.AddMinutes(2),
            SunderRpcContentRepeatability.SingleUse);
        try
        {
            for (var offset = 0; offset < content.Data.Length; offset += AgentChatContentTransferStore.ChunkBytes)
            {
                var length = Math.Min(AgentChatContentTransferStore.ChunkBytes, content.Data.Length - offset);
                _ = await InvokeAsync<RunControlChatContentChunk, AgentRpcEmpty>(
                    "stage-chat-content",
                    new(
                        Invocation,
                        new AgentChatContentChunk(
                            reference,
                            offset,
                            Convert.ToBase64String(content.Data.Span.Slice(offset, length)),
                            offset + length == content.Data.Length)),
                    cancellationToken).ConfigureAwait(false);
            }
            return reference;
        }
        catch
        {
            try
            {
                await DiscardChatContentAsync(reference.Id).ConfigureAwait(false);
            }
            catch
            {
            }
            throw;
        }
    }

    internal async ValueTask DiscardChatContentAsync(string contentId)
        => _ = await InvokeAsync<RunControlChatContentDiscard, AgentRpcEmpty>(
            "discard-chat-content",
            new(Invocation, contentId),
            CancellationToken.None).ConfigureAwait(false);

    private TResponse Invoke<TRequest, TResponse>(string methodId, TRequest request) where TRequest : notnull where TResponse : notnull
        => InvokeAsync<TRequest, TResponse>(methodId, request).AsTask().GetAwaiter().GetResult();

    private async ValueTask<TResponse> InvokeAsync<TRequest, TResponse>(string methodId, TRequest request, CancellationToken cancellationToken = default)
        where TRequest : notnull
        where TResponse : notnull
    {
        if (!_runControl.TryAcquire(out var lease))
        {
            throw new SunderRpcException(new SunderRpcError(SunderRpcErrorKind.StaleEndpoint, "agent.run-control.stale", "The Agent run-control provider activation is stale."));
        }
        using (lease)
        using (var invocation = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, lease.RetirementToken))
        {
            return await lease.Service.InvokeAsync<TRequest, TResponse>(methodId, request, invocation.Token).ConfigureAwait(false);
        }
    }

    private async IAsyncEnumerable<AgentChatStreamEvent> WithControlStream(
        Func<AgentRunControlRpcClient, IAsyncEnumerable<AgentChatStreamEvent>> subscribe,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        if (!_runControl.TryAcquire(out var lease))
        {
            throw new SunderRpcException(new SunderRpcError(SunderRpcErrorKind.StaleEndpoint, "agent.run-control.stale", "The Agent run-control provider activation is stale."));
        }
        using (lease)
        using (var invocation = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, lease.RetirementToken))
        {
            await foreach (var item in subscribe(lease.Service).WithCancellation(invocation.Token).ConfigureAwait(false)) yield return item;
        }
    }
}

internal sealed class AgentRunControlChatClient(AgentBehaviorLoopRuntimeRpcClient runtime, RunControlChatContext context) : IChatClient
{
    public async Task<ChatResponse> GetResponseAsync(IEnumerable<ChatMessage> messages, ChatOptions? options = null, CancellationToken cancellationToken = default)
        => await GetStreamingResponseAsync(messages, options, cancellationToken).ToChatResponseAsync(cancellationToken).ConfigureAwait(false);

    public async IAsyncEnumerable<ChatResponseUpdate> GetStreamingResponseAsync(IEnumerable<ChatMessage> messages, ChatOptions? options = null, [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var stagedContent = new List<SunderRpcContentReference>();
        var mappedMessages = new List<AgentChatMessage>();
        foreach (var message in messages)
        {
            var mappedContents = new List<AgentChatContent>(message.Contents.Count);
            foreach (var content in message.Contents)
            {
                if (content is DataContent data && !data.Data.IsEmpty)
                {
                    var reference = await runtime.StageChatContentAsync(data, cancellationToken).ConfigureAwait(false);
                    stagedContent.Add(reference);
                    mappedContents.Add(AgentChatWireMapper.FromContentReference(data, reference));
                }
                else
                {
                    mappedContents.Add(AgentChatWireMapper.FromContent(content));
                }
            }
            mappedMessages.Add(AgentChatWireMapper.FromChatMessage(message, mappedContents));
        }
        try
        {
            await foreach (var item in runtime.StreamChatAsync(
                               context,
                               mappedMessages,
                               AgentChatWireMapper.FromChatOptions(options),
                               cancellationToken).WithCancellation(cancellationToken).ConfigureAwait(false))
            {
                if (item.Kind == AgentChatStreamEvent.ErrorKind)
                {
                    throw new AgentChatProviderException(
                        item.ErrorMessage ?? "Provider request failed.",
                        item.ErrorContent ?? item.ErrorMessage ?? "Provider request failed.",
                        item.ErrorCode)
                    {
                        FailureKind = Enum.TryParse<AgentChatProviderFailureKind>(item.ErrorFailureKind, out var kind)
                            ? kind
                            : AgentChatProviderFailureKind.Unknown,
                    };
                }
                yield return AgentChatWireMapper.ToUpdate(item);
            }
        }
        finally
        {
            foreach (var reference in stagedContent)
            {
                try
                {
                    await runtime.DiscardChatContentAsync(reference.Id).ConfigureAwait(false);
                }
                catch
                {
                    // Staged content is bounded and expires if the run-control endpoint is unavailable.
                }
            }
        }
    }

    public object? GetService(Type serviceType, object? serviceKey = null) => null;
    public void Dispose() { }
}

public sealed record BehaviorLoopRunRequest(Guid InvocationId, AgentRpcProviderHandle RunControl, AgentBehaviorLoopContext Context);
public sealed record RunControlInvocation(Guid InvocationId);
public sealed record RunControlRecentTurnsRequest(RunControlInvocation Invocation, int Limit);
public sealed record RunControlSessionProjectionRequest(RunControlInvocation Invocation, AgentSessionPromptProjection Projection);
public sealed record RunControlActivityRequest(RunControlInvocation Invocation, AgentRunActivityKind Kind, string Text);
public sealed record RunControlBudgetChargeRequest(RunControlInvocation Invocation, AgentRunBudgetCharge Charge);
public sealed record RunControlPromptContextRequest(RunControlInvocation Invocation, IReadOnlyList<AgentPromptContextReceiptBlock> Blocks);
public sealed record RunControlCheckpointRequest(RunControlInvocation Invocation, AgentRunStatus Status, string? Summary);
public sealed record RunControlLogRequest(RunControlInvocation Invocation, PackageLogLevel Level, string EventName, string Message, long? ElapsedMilliseconds, IReadOnlyDictionary<string, string>? Attributes, string? ExceptionType, string? ExceptionMessage);
public sealed record RunControlAssistantTurnRequest(RunControlInvocation Invocation, AgentTurnRecord? AssistantTurn, string Content);
public sealed record RunControlCompleteTurnRequest(RunControlInvocation Invocation, AgentTurnRecord AssistantTurn);
public sealed record RunControlLifecycleRequest(RunControlInvocation Invocation, AgentLifecycleEventKind Kind, AgentRunStatus Status, AgentTurnRecord? TriggerTurn, AgentRunCheckpointRecord? Checkpoint, bool IsInterrupted);
public sealed record RunControlToolRequest(RunControlInvocation Invocation, AgentToolCallRequest ToolCall, AgentTurnRecord? AssistantTurn);
public sealed record RunControlToolsRequest(RunControlInvocation Invocation, IReadOnlyList<AgentToolCallRequest> ToolCalls, AgentTurnRecord? AssistantTurn);
public sealed record RunControlDefaultLoopRequest(RunControlInvocation Invocation, AgentBehaviorLoopContext Context);
public sealed record RunControlChatContentChunk(RunControlInvocation Invocation, AgentChatContentChunk Chunk);
public sealed record RunControlChatContentDiscard(RunControlInvocation Invocation, string ContentId);
public sealed record RunControlChatContext(string ProviderId, string ModelId, IReadOnlyDictionary<string, string>? CorrelationAttributes);
public sealed record RunControlChatRequest(RunControlInvocation Invocation, RunControlChatContext Context, IReadOnlyList<AgentChatMessage> Messages, AgentChatOptions Options);
