<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <SunderPackageProject>true</SunderPackageProject>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="AvaloniaEdit.TextMate" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="ModelContextProtocol" />
    <ProjectReference Include="..\Sunder.Package.Agent.Contracts\Sunder.Package.Agent.Contracts.csproj" />
  </ItemGroup>

  <Import Project="..\Sunder.Package.Agent.Shared\Sunder.Package.Agent.Shared.props" />

</Project>
