<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <SunderPackageProject>true</SunderPackageProject>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Google.GenAI" />
    <ProjectReference Include="..\Sunder.Package.Agent.Contracts\Sunder.Package.Agent.Contracts.csproj" />
  </ItemGroup>

  <Import Project="..\Sunder.Package.Agent.Shared\Sunder.Package.Agent.Shared.props" />
  <Import Project="..\Sunder.Package.Agent.Provider.Shared\Sunder.Package.Agent.Provider.Shared.props" />

</Project>
